// CODE GENERATED BY SPACE TOOLS. DO NOT EDIT FILE. YOUR CHANGES WILL BE LOST.
import { useNavigate } from "react-router-dom";
import { useEffect, useRef } from "react";
import { createClient } from "@supabase/supabase-js";

// Supabase env vars come from zo's secrets UI. Anon key is public-by-design.
const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL ||
  "https://oelfxzsaenqmmxtnhoex.supabase.co";
const SUPABASE_ANON_KEY =
  import.meta.env.VITE_SUPABASE_ANON_KEY ||
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9lbGZ4enNhZW5xbW14dG5ob2V4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzcxOTYwNTYsImV4cCI6MjA5Mjc3MjA1Nn0.iaLuNX0e8o_ks4Cd3S1W-4-BI60zyfIY1Mmqjaw_1zM";
const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

const css = `
@font-face {
  font-family: 'Mokgech';
  src: url('/fonts/mokgech.ttf') format('truetype');
  font-weight: normal;
  font-style: normal;
  font-display: swap;
}

* { margin: 0; padding: 0; box-sizing: border-box; }
html, body, #root { width: 100%; height: 100%; overflow: hidden; background: #000; }

.landing-root {
  position: fixed;
  inset: 0;
  width: 100vw;
  height: 100vh;
  overflow: hidden;
  background: #000;
}

.landing-video {
  position: absolute;
  inset: 0;
  width: 100%;
  height: 100%;
  object-fit: cover;
  z-index: 1;
  pointer-events: none;
  /* Faint darkening so the title pops without obscuring the scene */
  filter: brightness(0.85);
}

.landing-vignette {
  position: absolute;
  inset: 0;
  z-index: 2;
  pointer-events: none;
  background: radial-gradient(ellipse at center, transparent 30%, rgba(0,0,0,0.45) 100%);
}

.landing-title-wrap {
  position: absolute;
  inset: 0;
  z-index: 3;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 4vw;
}

.landing-title {
  font-family: 'Mokgech', serif;
  /* Keep font-weight normal — Mokgech's character is in the strokes themselves */
  font-weight: normal;
  color: #f1dca7;
  text-transform: uppercase;
  letter-spacing: 0.08em;
  line-height: 1.1;
  text-align: center;
  cursor: pointer;
  user-select: none;
  font-size: clamp(2.4rem, 7vw, 7rem);
  /* Layered glow + dark shadow so it reads against any cloud color */
  text-shadow:
    0 2px 8px rgba(0, 0, 0, 0.85),
    0 0 24px rgba(241, 220, 167, 0.35),
    0 0 64px rgba(255, 180, 80, 0.25);
  transition: transform 0.3s ease, text-shadow 0.3s ease, color 0.3s ease;
  max-width: 16ch;
}

.landing-title:hover,
.landing-title:focus-visible {
  color: #ffeec7;
  transform: scale(1.02);
  text-shadow:
    0 2px 12px rgba(0, 0, 0, 0.9),
    0 0 36px rgba(255, 220, 140, 0.6),
    0 0 96px rgba(255, 180, 80, 0.45);
  outline: none;
}

.landing-hint {
  position: absolute;
  bottom: 5vh;
  left: 0;
  right: 0;
  z-index: 3;
  text-align: center;
  color: rgba(241, 220, 167, 0.6);
  font-family: 'Mokgech', serif;
  font-size: clamp(0.7rem, 1.1vw, 1rem);
  letter-spacing: 0.3em;
  text-transform: uppercase;
  text-shadow: 0 1px 4px rgba(0,0,0,0.7);
  pointer-events: none;
}

@media (max-width: 640px) {
  .landing-title { max-width: 12ch; }
}
`;

export default function Page() {
  const navigate = useNavigate();
  const videoRef = useRef<HTMLVideoElement>(null);

  // If the visitor is already signed in, skip the landing entirely.
  // We DO NOT block render on this — the video starts immediately for everyone;
  // a navigate call inside the effect happens before a frame is committed in
  // most cases when there IS a session.
  useEffect(() => {
    let active = true;
    supabase.auth.getSession().then(({ data }) => {
      if (!active) return;
      if (data.session) navigate("/chat", { replace: true });
    });
    return () => {
      active = false;
    };
  }, [navigate]);

  // Some mobile browsers refuse to start the video without a kick. This helps.
  useEffect(() => {
    const v = videoRef.current;
    if (!v) return;
    const tryPlay = () => v.play().catch(() => {});
    tryPlay();
    document.addEventListener("touchstart", tryPlay, { once: true });
    return () => document.removeEventListener("touchstart", tryPlay);
  }, []);

  function enterFlight() {
    // Fullscreen requires a user gesture; the click event qualifies. We try it
    // synchronously here, then navigate to /auth (or /chat if already signed in,
    // which is handled by /auth's own effect). Because react-router does SPA
    // navigation on the same document, the fullscreen state persists across routes.
    const root = document.documentElement;
    const req =
      root.requestFullscreen ||
      // @ts-expect-error vendor prefixes
      root.webkitRequestFullscreen ||
      // @ts-expect-error vendor prefixes
      root.msRequestFullscreen;
    if (req) {
      try {
        const promise = req.call(root);
        if (promise && typeof (promise as Promise<void>).catch === "function") {
          (promise as Promise<void>).catch(() => {});
        }
      } catch {
        // ignore — fullscreen is a nice-to-have, not a requirement
      }
    }
    navigate("/auth");
  }

  function onKey(e: React.KeyboardEvent<HTMLDivElement>) {
    if (e.key === "Enter" || e.key === " ") {
      e.preventDefault();
      enterFlight();
    }
  }

  return (
    <div className="landing-root">
      <style>{css}</style>
      <video
        ref={videoRef}
        className="landing-video"
        src="/videos/phoenix-loop.mp4"
        autoPlay
        loop
        muted
        playsInline
        preload="auto"
      />
      <div className="landing-vignette" />
      <div className="landing-title-wrap">
        <div
          className="landing-title"
          role="button"
          tabIndex={0}
          onClick={enterFlight}
          onKeyDown={onKey}
          aria-label="Enter the Flight of the Phoenix"
        >
          Welcome to the Flight of the Phoenix
        </div>
      </div>
      <div className="landing-hint">Click to enter</div>
    </div>
  );
}
