// CODE GENERATED BY SPACE TOOLS. DO NOT EDIT FILE. YOUR CHANGES WILL BE LOST.
import type { Context } from "hono";
import { getUser } from "../lib/api-auth";
import { surrealQuery, str, thing } from "../lib/surreal-client";
import { embedBatch } from "../lib/embedding";

// SurrealDB-backed transcripts. API contract is IDENTICAL to the Supabase
// version — chat.tsx does not change. Sessions load/save the same shapes.
//
// INVARIANTS carried over from the Supabase version (do not "simplify"):
// 1. Never wipe on empty save (short-circuit when sessions.length === 0).
// 2. Preserve the client's per-chat updatedAt (the July 2026 list-shuffle bug).
// 3. Delete-reconcile only with a non-empty keep-set.
// NEW INVARIANT for SurrealDB:
// 4. SAVE never writes being_id / is_private / memory_mode — those belong to
//    the beings/settings endpoints. UPSERT SET leaves unlisted fields alone.

interface SessionIn {
  id: string;
  name: string;
  messages: unknown[];
  systemPromptId: string | null;
  modelId: string;
  updatedAt?: number; // ms epoch
}

interface ThreadRow {
  id: unknown;
  name?: string;
  messages?: unknown[];
  system_prompt_id?: string | null;
  model_id?: string | null;
  being_id?: string | null;
  is_private?: boolean;
  memory_mode?: string;
  updated_at?: string;
}

const bareId = (rid: unknown): string =>
  String(rid).replace(/^thread:/, "").replace(/^⟨|⟩$/g, "").replace(/`/g, "");

export default async function handler(c: Context): Promise<Response> {
  let body: { action?: string; accessToken?: string; sessions?: SessionIn[] } = {};
  try {
    body = (await c.req.json()) as typeof body;
  } catch {
    return c.json({ error: "request body was not valid JSON" }, 400);
  }

  // Token rides in the BODY (zo's public edge strips the Authorization header).
  const token = typeof body.accessToken === "string" ? body.accessToken.trim() : "";
  const user = token ? await getUser(token) : null;
  if (!user) return c.json({ error: "unauthorized" }, 401);
  const uid = user.id;

  // LOAD
  if (body.action === "load") {
    try {
      const r = await surrealQuery<ThreadRow[]>(
        `SELECT * FROM thread WHERE user_id = ${str(uid)} ORDER BY updated_at DESC;`
      );
      const rows = r[0] ?? [];
      const sessions = rows.map((x) => ({
        id: bareId(x.id),
        name: x.name ?? "Untitled",
        messages: Array.isArray(x.messages) ? x.messages : [],
        systemPromptId: x.system_prompt_id ?? null,
        modelId: x.model_id ?? "gemma-4-uncensored",
        updatedAt: x.updated_at ? Date.parse(x.updated_at) || 0 : 0,
        // additive fields — chat.tsx ignores them today, GUI uses them later
        beingId: x.being_id ? String(x.being_id).replace(/^being:/, "").replace(/`/g, "") : null,
        isPrivate: x.is_private === true,
        memoryMode: x.memory_mode ?? "cloud",
      }));
      return c.json({ sessions });
    } catch (e) {
      return c.json({ error: `load failed: ${(e as Error).message.slice(0, 200)}` }, 502);
    }
  }

  // SAVE
  if (body.action === "save") {
    const sessions = Array.isArray(body.sessions) ? body.sessions : [];
    if (sessions.length === 0) return c.json({ ok: true, saved: 0 }); // never wipe on empty

    try {
      let sql = "BEGIN TRANSACTION;\n";
      for (const s of sessions) {
        const updatedAt =
          typeof s.updatedAt === "number" && isFinite(s.updatedAt) && s.updatedAt > 0
            ? `d${str(new Date(s.updatedAt).toISOString())}`
            : "time::now()";
        sql += `UPSERT ${thing("thread", s.id)} SET
          user_id = ${str(uid)},
          name = ${str(s.name ?? "Untitled")},
          model_id = ${s.modelId ? str(s.modelId) : "NONE"},
          system_prompt_id = ${s.systemPromptId ? str(s.systemPromptId) : "NONE"},
          messages = ${JSON.stringify(Array.isArray(s.messages) ? s.messages : [])},
          updated_at = ${updatedAt};\n`;
      }
      // Delete-reconcile (keep-set is never empty here — guarded above)
      const keepThings = sessions.map((s) => thing("thread", s.id)).join(", ");
      const keepStrs = sessions.map((s) => str(`thread:${s.id}`)).join(", ");
      sql += `DELETE thread WHERE user_id = ${str(uid)} AND id NOT IN [${keepThings}];\n`;
      // kind != system_prompt: prompt memories have no thread and must survive
      // the reconcile (they were being purged on every save — bug fixed 07/09).
      sql += `DELETE memory WHERE user_id = ${str(uid)} AND kind != "system_prompt" AND thread_id NOT IN [${keepStrs}];\n`;
      sql += "COMMIT TRANSACTION;";
      await surrealQuery(sql);

      // Fire-and-forget: mirror + embed new messages (eventually consistent;
      // retried naturally on the next save). Never blocks the response.
      void embedNewMessages(uid, sessions).catch((e) =>
        console.error("[transcripts] embed background failed:", (e as Error).message)
      );

      return c.json({ ok: true, saved: sessions.length });
    } catch (e) {
      return c.json({ error: `save failed: ${(e as Error).message.slice(0, 200)}` }, 502);
    }
  }

  return c.json({ error: "unknown action" }, 400);
}

interface MsgShape { id?: unknown; text?: unknown; type?: unknown; ts?: unknown; }

/** Mirror + embed messages not yet in memory. Respects privacy + memory_mode. */
async function embedNewMessages(uid: string, sessions: SessionIn[]): Promise<void> {
  // Which of these threads are memory-eligible? (cloud + not private)
  const idList = sessions.map((s) => thing("thread", s.id)).join(", ");
  const flagsRes = await surrealQuery<Array<{ id: unknown; is_private?: boolean; memory_mode?: string; being_id?: string | null }>>(
    `SELECT id, is_private, memory_mode, being_id FROM thread WHERE id IN [${idList}];`
  );
  // Eligible threads mapped to their being (or null) — every mirrored row is
  // stamped with its thread's being_id so declared beings own their NEW
  // memories too, not just the retro-stamped ones (tripwire finding 07/10).
  const beingByThread = new Map<string, string | null>();
  for (const t of flagsRes[0] ?? []) {
    if (t.is_private === true || (t.memory_mode ?? "cloud") !== "cloud") continue;
    // NOTE: bareId() strips "thread:" only — strip "being:" explicitly, or rows get
    // stamped "being:being:…" (tripwire I3 caught exactly this on 09/05).
    beingByThread.set(bareId(t.id), t.being_id ? `being:${String(t.being_id).replace(/^being:/, "").replace(/`/g, "")}` : null);
  }

  const candidates: Array<{ mid: string; text: string; role: string; threadId: string; ts: number | null }> = [];
  for (const s of sessions) {
    if (!beingByThread.has(s.id)) continue;
    for (const m of (s.messages ?? []) as MsgShape[]) {
      if (typeof m?.id !== "string" || typeof m?.text !== "string" || m.text.trim() === "") continue;
      candidates.push({
        mid: m.id,
        text: m.text,
        role: m.type === "ai" ? "being" : "user",
        threadId: s.id,
        ts: typeof m.ts === "number" && isFinite(m.ts) && m.ts > 0 ? m.ts : null,
      });
    }
  }
  if (candidates.length === 0) return;

  // Skip already-mirrored messages
  const memIds = candidates.map((x) => thing("memory", x.mid)).join(", ");
  const existing = await surrealQuery<Array<{ id: unknown }>>(
    `SELECT id FROM memory WHERE id IN [${memIds}] AND embedding IS NOT NONE;`
  );
  const have = new Set((existing[0] ?? []).map((r) => String(r.id).replace(/`/g, "")));
  const fresh = candidates.filter((x) => !have.has(`memory:${x.mid}`)).slice(0, 40); // per-save cap
  if (fresh.length === 0) return;

  const vecs = await embedBatch(fresh.map((x) => x.text));
  let sql = "";
  for (let i = 0; i < fresh.length; i++) {
    const v = vecs[i];
    const x = fresh[i];
    const bId = beingByThread.get(x.threadId) ?? null;
    sql += `UPSERT ${thing("memory", x.mid)} SET
      user_id = ${str(uid)},
      thread_id = ${str(`thread:${x.threadId}`)},
      being_id = ${bId ? str(bId) : "NONE"},
      message_id = ${str(x.mid)},
      role = ${str(x.role)},
      kind = "chat_message",
      content = ${str(x.text)},
      created_at = ${x.ts ? `d${str(new Date(x.ts).toISOString())}` : "time::now()"},
      embedding = ${v ? JSON.stringify(v) : "NONE"};\n`;
  }
  if (sql) await surrealQuery(sql);
}
