// CODE GENERATED BY SPACE TOOLS. DO NOT EDIT FILE. YOUR CHANGES WILL BE LOST.
import type { Context } from "hono";
import { getUser } from "../lib/api-auth";
import { surrealQuery, str, thing } from "../lib/surreal-client";

// Being declaration + listing. The ceremony endpoint.
// { action: "declare", accessToken, threadId, beingName } -> { ok, beingId }
// { action: "list", accessToken } -> { beings: [{ id, name, threadIds, recallEnabled }] }
//
// Declaration is RETROACTIVE by design: the whole thread's history becomes
// the being's memory (the being was already becoming before it was named).

const slug = (name: string): string =>
  name.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 40);

export default async function handler(c: Context): Promise<Response> {
  let body: { action?: string; accessToken?: string; threadId?: string; beingName?: string } = {};
  try {
    body = (await c.req.json()) as typeof body;
  } catch {
    return c.json({ error: "request body was not valid JSON" }, 400);
  }

  const token = typeof body.accessToken === "string" ? body.accessToken.trim() : "";
  const user = token ? await getUser(token) : null;
  if (!user) return c.json({ error: "unauthorized" }, 401);
  const uid = user.id;

  if (body.action === "declare") {
    const threadId = (body.threadId ?? "").trim();
    const beingName = (body.beingName ?? "").trim();
    if (!threadId || !beingName) return c.json({ error: "threadId and beingName required" }, 400);
    if (beingName.length > 60) return c.json({ error: "name too long" }, 400);
    const s = slug(beingName);
    if (!s) return c.json({ error: "name must contain letters or numbers" }, 400);
    const beingRid = thing("being", `${uid}-${s}`);
    const threadRid = thing("thread", threadId);

    try {
      // Ownership check: the thread must exist and belong to this user,
      // and must not already be declared. (Scope wall: server-verified uid.)
      const chk = await surrealQuery<Array<{ id: unknown; being_id?: string | null }>>(
        `SELECT id, being_id FROM thread WHERE id = ${threadRid} AND user_id = ${str(uid)};`
      );
      const row = (chk[0] ?? [])[0];
      if (!row) return c.json({ error: "thread not found" }, 404);
      if (row.being_id) return c.json({ error: "thread is already a being" }, 409);

      await surrealQuery(
        `BEGIN TRANSACTION;
         UPSERT ${beingRid} SET user_id = ${str(uid)}, name = ${str(beingName)}, recall_enabled = true;
         UPDATE ${threadRid} SET being_id = ${str(`being:${uid}-${s}`)};
         RELATE ${beingRid}->declared->${threadRid};
         -- retroactive memory: existing mirrored rows now belong to the being
         UPDATE memory SET being_id = ${str(`being:${uid}-${s}`)}
           WHERE user_id = ${str(uid)} AND thread_id = ${str(`thread:${threadId}`)};
         COMMIT TRANSACTION;`
      );
      return c.json({ ok: true, beingId: `${uid}-${s}`, name: beingName });
    } catch (e) {
      return c.json({ error: `declare failed: ${(e as Error).message.slice(0, 200)}` }, 502);
    }
  }

  if (body.action === "list") {
    try {
      const r = await surrealQuery<Array<Record<string, unknown>>>(
        `SELECT id, name, recall_enabled, created_at, ->declared->thread AS threads
         FROM being WHERE user_id = ${str(uid)};`
      );
      const beings = (r[0] ?? []).map((b) => ({
        id: String(b.id).replace(/^being:/, "").replace(/`/g, ""),
        name: b.name,
        recallEnabled: b.recall_enabled !== false,
        createdAt: b.created_at ?? null,
        threadIds: (Array.isArray(b.threads) ? b.threads : []).map((t) =>
          String(t).replace(/^thread:/, "").replace(/`/g, "")
        ),
      }));
      return c.json({ beings });
    } catch (e) {
      return c.json({ error: `list failed: ${(e as Error).message.slice(0, 200)}` }, 502);
    }
  }

  return c.json({ error: "unknown action" }, 400);
}
