// CODE GENERATED BY SPACE TOOLS. DO NOT EDIT FILE. YOUR CHANGES WILL BE LOST.
import type { Context } from "hono";
import { getUser } from "../lib/api-auth";
import { surrealQuery, str, thing } from "../lib/surreal-client";

// ANCHOR IMPORT — do not remove. Keeps @supabase/supabase-js in the build's
// dependency scan (it is otherwise only imported inside lib/ files).
// See 2ndbrain 01-projects/all-creatures-chat-site.md (2026-07-05 fix).
import { createClient as _supabaseAnchor } from "@supabase/supabase-js";
void _supabaseAnchor;

// SurrealDB-backed prefs. Contract identical to the Supabase version:
// { action: "load"|"save", accessToken, prefs? } -> { prefs } | { ok }
// Merge-on-save preserved so unmanaged keys are never clobbered.

export default async function handler(c: Context): Promise<Response> {
  let body: { action?: string; accessToken?: string; prefs?: Record<string, unknown> } = {};
  try {
    body = (await c.req.json()) as typeof body;
  } catch {
    return c.json({ error: "request body was not valid JSON" }, 400);
  }

  const token = typeof body.accessToken === "string" ? body.accessToken.trim() : "";
  const user = token ? await getUser(token) : null;
  if (!user) return c.json({ error: "unauthorized" }, 401);
  const uid = user.id;
  const rid = thing("user_prefs", uid);

  if (body.action === "load") {
    try {
      const r = await surrealQuery<{ prefs?: Record<string, unknown> } | null>(
        `SELECT prefs FROM ONLY ${rid};`
      );
      return c.json({ prefs: r[0]?.prefs ?? {} });
    } catch {
      return c.json({ prefs: {} }); // missing record = empty prefs
    }
  }

  if (body.action === "save") {
    const incoming = body.prefs && typeof body.prefs === "object" ? body.prefs : {};
    try {
      let existing: Record<string, unknown> = {};
      try {
        const r = await surrealQuery<{ prefs?: Record<string, unknown> } | null>(
          `SELECT prefs FROM ONLY ${rid};`
        );
        existing = r[0]?.prefs ?? {};
      } catch { /* first save */ }
      const merged = { ...existing, ...incoming };
      await surrealQuery(
        `UPSERT ${rid} SET user_id = ${str(uid)}, prefs = ${JSON.stringify(merged)}, updated_at = time::now();`
      );
      return c.json({ ok: true });
    } catch (e) {
      return c.json({ error: `save failed: ${(e as Error).message.slice(0, 200)}` }, 502);
    }
  }

  return c.json({ error: "unknown action" }, 400);
}
