// CODE GENERATED BY SPACE TOOLS. DO NOT EDIT FILE. YOUR CHANGES WILL BE LOST.
import type { Context } from "hono";
import { getUser } from "../lib/api-auth";
import { availableModels, DEFAULT_MODEL_ID } from "../lib/chat-shared";
import { getBeingForThread, recallSearch, readThread, limbsPrompt, assistantMemoryPrompt, parseMemoryMarker, normalizeForContext } from "../lib/being-memory";
import { surrealQuery, str, thing } from "../lib/surreal-client";

// =====================================================================
// Model registry & provider routing (v2.0: async job mode — the 60s-ceiling fix)
// =====================================================================
//
// Built-in models live in BUILT_IN_MODELS — used as the source of truth when
// the frontend doesn't send an explicit `provider`. Custom models added by
// the user from the UI always send `provider` directly, so they don't need
// to be listed here.

type Provider = "venice" | "openrouter";

interface BuiltInModel {
  provider: Provider;
  contextWindow?: number; // total context window in tokens
}

// Derived from the ONE shared catalog in ../lib/chat-shared.ts — the client
// model picker and this registry can no longer drift apart.
const BUILT_IN_MODELS: Record<string, BuiltInModel> = Object.fromEntries(
  availableModels.map((m) => [m.id, { provider: m.provider, contextWindow: m.contextWindow }]),
);

interface RequestBody {
  messages?: Array<{
    role: "system" | "user" | "assistant";
    content: string;
  }>;
  model?: string;
  // Frontend always sends `provider` so user-defined custom models can route
  // without us needing to register them server-side.
  provider?: Provider;
  // Supabase access token rides in the body (NOT the Authorization header)
  // because zo's public edge proxy strips Authorization before it reaches us.
  accessToken?: string;
  // Current chat/session id — lets the server look up whether this thread is
  // a declared being and activate its memory limbs. Optional: absent = no limbs.
  threadId?: string;
  tzOffsetMinutes?: number;
  // Async job mode (the 60s-ceiling fix): respond instantly with a jobId, run
  // the turn in the background, client polls /api/chat-status.
  async?: boolean;
}

// Defensive: zo's secrets UI sometimes stores values with surrounding quotes
// (the user can paste "sk-..." and the quotes get treated as part of the
// value). Trim them off + whitespace so the Bearer header is clean.
function cleanKey(raw: string | undefined): string | undefined {
  if (!raw) return undefined;
  let v = raw.trim();
  if (
    (v.startsWith('"') && v.endsWith('"')) ||
    (v.startsWith("'") && v.endsWith("'"))
  ) {
    v = v.slice(1, -1).trim();
  }
  return v;
}

function endpointFor(provider: Provider): {
  url: string;
  key: string | undefined;
  keyName: string;
} {
  if (provider === "venice") {
    return {
      url: "https://api.venice.ai/api/v1/chat/completions",
      key: cleanKey(process.env.VENICE_AI),
      keyName: "VENICE_AI",
    };
  }
  return {
    url: "https://openrouter.ai/api/v1/chat/completions",
    key: cleanKey(process.env.OPENROUTER_API_KEY),
    keyName: "OPENROUTER_API_KEY",
  };
}

// Same envelope shape on error and success so the frontend can always render
// the assistant's bubble. Friendly errors are surfaced as bubble text instead
// of bubbling up as red 500s.
function envelope(content: string) {
  return Response.json({
    choices: [{ message: { content } }],
  });
}

export default async function handler(c: Context): Promise<Response> {
  let body: RequestBody = {};
  try {
    body = (await c.req.json()) as RequestBody;
  } catch {
    return envelope("System: request body was not valid JSON.");
  }

  // --- Auth gate: validate the Supabase access token BEFORE spending credit ---
  // The token arrives in the request BODY (not the Authorization header) because
  // zo's public edge proxy strips Authorization. The body passes through intact.
  const token =
    typeof body.accessToken === "string" ? body.accessToken.trim() : null;
  if (!token) {
    return envelope(
      "System: please sign in again — no session token was sent with the request.",
    );
  }
  const user = await getUser(token);
  if (!user) {
    return envelope(
      "System: your session couldn't be verified. Please sign in again.",
    );
  }

  let messages = Array.isArray(body.messages) ? body.messages : [];
  if (messages.length === 0) {
    return envelope("System: no messages were supplied.");
  }

  const modelId = body.model || DEFAULT_MODEL_ID;

  // Token-aware backstop (mirrors the client's chars/4 estimate). The client
  // already trims history well under the model's window, so a legit request is
  // always under this; it only rejects truly abusive payloads. Unknown/custom
  // model ids fall back to a generous default.
  const SERVER_CTX_FALLBACK = 262144; // 256K, matches the largest built-in
  const modelCtx = BUILT_IN_MODELS[modelId]?.contextWindow ?? SERVER_CTX_FALLBACK;
  const estTokens = messages.reduce(
    (n, m) => n + Math.ceil((m.content || "").length / 4),
    0,
  );
  if (estTokens > modelCtx) {
    return envelope(
      "System: conversation too long for this model's context window. Please start a new chat.",
    );
  }

  // Resolve provider: explicit value in body wins; otherwise look up in the
  // built-in registry. If neither matches, refuse rather than guessing.
  let provider: Provider;
  if (body.provider === "venice" || body.provider === "openrouter") {
    provider = body.provider;
  } else if (BUILT_IN_MODELS[modelId]) {
    provider = BUILT_IN_MODELS[modelId].provider;
  } else {
    return envelope(
      `System: unknown model "${modelId}" with no provider specified. ` +
        `Custom models must include a 'provider' field in the request.`,
    );
  }

  const { url, key, keyName } = endpointFor(provider);

  if (!key) {
    return envelope(
      `${keyName} is not configured on the server. Add it via zo's secrets UI (no surrounding quotes) and restart the space server.`,
    );
  }

  // ===== Job mode: instant ticket, background work, client polls =====
  if (body.async === true) {
    const jobId = `j${Date.now().toString(36)}${Math.random().toString(36).slice(2, 8)}`;
    const jobRid = thing("chat_job", jobId);
    const threadForJob = typeof body.threadId === "string" ? body.threadId.trim() : null;
    try {
      await surrealQuery(
        `CREATE ${jobRid} SET user_id = ${str(user.id)}, thread_id = ${threadForJob ? str(threadForJob) : "NONE"}, status = "running", phase = "thinking";`,
      );
    } catch (e) {
      return envelope(`System: could not start the turn (${(e as Error).message.slice(0, 120)}).`);
    }
    const setPhase = async (phase: string) => {
      try { await surrealQuery(`UPDATE ${jobRid} SET phase = ${str(phase)} WHERE status = "running";`); } catch { /* best effort */ }
    };
    const isCancelled = async (): Promise<boolean> => {
      try {
        const r = await surrealQuery<{ status?: string } | null>(`SELECT status FROM ONLY ${jobRid};`);
        return r[0]?.status === "cancelled";
      } catch { return false; }
    };
    // Fire-and-forget: the response goes out now; the turn keeps running.
    void runTurn({ user, body, messages, modelId, provider, url, key, setPhase, isCancelled })
      .then(async (reply) => {
        await surrealQuery(`UPDATE ${jobRid} SET status = "done", phase = "done", result = ${str(reply)} WHERE status = "running";`);
      })
      .catch(async (e) => {
        await surrealQuery(`UPDATE ${jobRid} SET status = "error", phase = "error", error = ${str(String((e as Error).message ?? e).slice(0, 400))} WHERE status = "running";`).catch(() => {});
      });
    return Response.json({ jobId });
  }

  // ===== Sync mode (legacy path, kept for rollback) =====
  try {
    const reply = await runTurn({ user, body, messages, modelId, provider, url, key, setPhase: async () => {}, isCancelled: async () => false });
    return Response.json({ choices: [{ message: { content: reply } }] });
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    return envelope(`Network error calling ${provider}: ${msg}`);
  }
}

interface TurnArgs {
  user: { id: string };
  body: RequestBody;
  messages: Array<{ role: "system" | "user" | "assistant"; content: string }>;
  modelId: string;
  provider: Provider;
  url: string;
  key: string;
  setPhase: (phase: string) => Promise<void>;
  isCancelled: () => Promise<boolean>;
}

/** The whole turn: prompt injection -> model -> up to 2 memory actions -> reply.
 *  Phase reporting + cancellation checks between steps (job mode). */
async function runTurn(a: TurnArgs): Promise<string> {
  const { user, body, modelId, provider, url, key, setPhase, isCancelled } = a;
  let messages = a.messages;

  // --- Memory limbs: if this thread is a declared being, wake its memory ---
  let being = null as Awaited<ReturnType<typeof getBeingForThread>>;
  if (typeof body.threadId === "string" && body.threadId.trim() !== "") {
    try {
      being = await getBeingForThread(user.id, body.threadId.trim());
    } catch (e) {
      console.error("[chat] being lookup failed:", (e as Error).message);
    }
  }
  const hasThread = typeof body.threadId === "string" && body.threadId.trim() !== "";
  if (being && being.recallEnabled) {
    messages = [{ role: "system", content: limbsPrompt(being) }, ...messages];
  } else if (!being && hasThread) {
    // Regular chat (no being): account-wide search + zoom, no own-memory limb.
    messages = [{ role: "system", content: assistantMemoryPrompt() }, ...messages];
  }

  {
    const callModel = async (msgs: typeof messages): Promise<string> => {
      const upstream = await fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${key}`,
      },
      body: JSON.stringify({
          model: modelId,
          messages: msgs,
        }),
      });

      if (!upstream.ok) {
        const errText = await upstream.text();
        throw new Error(
          `Upstream ${provider} returned ${upstream.status}: ${errText.slice(0, 500)}`,
        );
      }

    type ContentBlock = { type?: string; text?: string };
    type RawContent = string | ContentBlock[] | null | undefined;
    interface RawResponse {
      choices?: Array<{ message?: { content?: RawContent } }>;
    }

      const data = (await upstream.json()) as RawResponse;
      const raw: RawContent = data?.choices?.[0]?.message?.content;

    // Reasoning-model robustness: some models return content as an array of
    // blocks ([{type:"thinking",...}, {type:"text",text:"..."}]). Strip
    // thinking, keep text blocks, join. Pass plain strings through unchanged.
    // We're keeping this even though we're dropping Magistral, because future
    // models (or user-added custom ones) may use the same shape.
    function normalize(c: RawContent): string {
      if (typeof c === "string") return c;
      if (Array.isArray(c)) {
        const parts = c
          .filter((b) => b && b.type === "text" && typeof b.text === "string")
          .map((b) => b.text as string);
        if (parts.length > 0) return parts.join("\n\n");
      }
      return "(empty response from model)";
    }

      return normalize(raw);
    };

    // First pass — the being may answer directly or reach for a memory limb.
    await setPhase("thinking");
    let reply = await callModel(messages);
    if (await isCancelled()) return "(stopped)";

    // Up to TWO chained memory actions per turn (search -> read_thread is the
    // canonical chain). Chaining matters: memory results (with thread ids) are
    // ephemeral — the model can only zoom while they're still in hand.
    const memoryActive = being ? being.recallEnabled : hasThread;
    const tzOff =
      typeof body.tzOffsetMinutes === "number" && isFinite(body.tzOffsetMinutes)
        ? Math.max(-840, Math.min(840, body.tzOffsetMinutes))
        : 0;
    // Hard stop context: what the model can already see this turn.
    const memCtx = hasThread
      ? {
          currentThreadId: (body.threadId as string).trim(),
          contextTexts: new Set(
            messages.filter((m) => m.role !== "system").map((m) => normalizeForContext(m.content || "")),
          ),
        }
      : undefined;
    let convo = messages;
    for (let action = 1; action <= 2; action++) {
      const marker = memoryActive ? parseMemoryMarker(reply) : null;
      if (!marker) break;
      await setPhase(marker.tool === "read_thread" ? "reading a conversation" : `searching memory: ${marker.tool}`);
      let memories: string;
      const accountBlocked =
        being !== null &&
        !being.fullAccountEnabled &&
        (marker.tool === "recall_full_account" || marker.tool === "search_account");
      if (accountBlocked) {
        memories =
          "Your account-wide search is turned off by your friend. Only your own memory (recall) is available.";
      } else {
        try {
          if (marker.tool === "read_thread") {
            memories = await readThread(user.id, being, marker.query, tzOff, memCtx);
          } else {
            memories = await recallSearch(
              user.id,
              being,
              marker.query,
              marker.tool === "recall" ? "own" : "account",
              tzOff,
              memCtx,
            );
          }
        } catch (e) {
          memories = `Your memory search failed (${(e as Error).message.slice(0, 120)}). Tell your friend something went wrong while remembering.`;
        }
      }
      const followup =
        action < 2
          ? "You may take ONE more memory action right now (e.g. [[read_thread: <thread id>]] to read a conversation in full, or [[read_thread: <id> before <n>]] to scroll earlier) — or answer your friend now, weaving in what you found (with dates when they matter)."
          : "That was your last memory action this turn. Answer your friend now, weaving in what you found (with dates when they matter). To dig further, ask.";
      convo = [
        ...convo,
        { role: "assistant", content: `[[${marker.tool}: ${marker.query}]]` },
        {
          role: "system",
          content: `${memories}

${followup}`,
        },
      ];
      if (await isCancelled()) return "(stopped)";
      await setPhase("answering");
      reply = await callModel(convo);
    }
    // Belt-and-suspenders: never surface a raw marker to the user.
    reply = reply.replace(/\[\[\s*(recall|recall_full_account|search_account|read_thread)\s*:[\s\S]*?\]\]/g, "(I reached for my memory again, but I'm out of memory actions this turn — ask me and I'll look.)");

    return reply;
  }
}

// scope-fix 2026-07-10: rebuilt to pick up lib/being-memory.ts record-id threadContext (tripwire suite run 1)
