// CODE GENERATED BY SPACE TOOLS. DO NOT EDIT FILE. YOUR CHANGES WILL BE LOST.
import type { Context } from "hono";
import { getUser } from "../lib/api-auth";
import { surrealQuery, str, thing } from "../lib/surreal-client";

// Job status + cancel for the async chat pipeline (the 60s-ceiling fix).
// { action: "status", accessToken, jobId } -> { status, phase, result?, error? }
// { action: "cancel", accessToken, jobId } -> { ok }
// Jobs are owned: a user can only see/cancel their own.

interface JobRow {
  id: unknown;
  user_id?: string;
  status?: string; // running | done | error | cancelled
  phase?: string;  // thinking | searching memory: recall | reading a conversation | answering | done
  result?: string | null;
  error?: string | null;
}

export default async function handler(c: Context): Promise<Response> {
  let body: { action?: string; accessToken?: string; jobId?: string } = {};
  try {
    body = (await c.req.json()) as typeof body;
  } catch {
    return c.json({ error: "request body was not valid JSON" }, 400);
  }
  const token = typeof body.accessToken === "string" ? body.accessToken.trim() : "";
  const user = token ? await getUser(token) : null;
  if (!user) return c.json({ error: "unauthorized" }, 401);
  const jobId = (body.jobId ?? "").trim().replace(/[^a-zA-Z0-9_-]/g, "");
  if (!jobId) return c.json({ error: "jobId required" }, 400);
  const rid = thing("chat_job", jobId);

  try {
    const r = await surrealQuery<JobRow | null>(`SELECT * FROM ONLY ${rid};`);
    const job = r[0];
    if (!job || job.user_id !== user.id) return c.json({ error: "job not found" }, 404);

    if (body.action === "cancel") {
      if (job.status === "running") {
        await surrealQuery(`UPDATE ${rid} SET status = "cancelled", phase = "stopped";`);
      }
      return c.json({ ok: true });
    }
    // default: status
    return c.json({
      status: job.status ?? "running",
      phase: job.phase ?? "thinking",
      result: job.status === "done" ? job.result ?? "" : undefined,
      error: job.status === "error" ? job.error ?? "unknown error" : undefined,
    });
  } catch (e) {
    return c.json({ error: `status failed: ${(e as Error).message.slice(0, 200)}` }, 502);
  }
}
