// CODE GENERATED BY SPACE TOOLS. DO NOT EDIT FILE. YOUR CHANGES WILL BE LOST.
// CODE GENERATED BY SPACE TOOLS. DO NOT EDIT FILE. YOUR CHANGES WILL BE LOST.
import type { Context } from "hono";

// --- Supabase token validation (Path A: raw HTTPS, no supabase-js client) ---
// The browser-oriented supabase-js client misbehaves server-side (it expects
// browser storage), so we validate the caller's access token with a plain
// fetch to Supabase's GoTrue /auth/v1/user endpoint — exactly what getUser()
// does internally, minus the client baggage. Anon key is public-by-design.
const SUPABASE_URL =
  process.env.VITE_SUPABASE_URL ||
  process.env.SUPABASE_URL ||
  "https://oelfxzsaenqmmxtnhoex.supabase.co";
const SUPABASE_ANON_KEY =
  process.env.VITE_SUPABASE_ANON_KEY ||
  process.env.SUPABASE_ANON_KEY ||
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9lbGZ4enNhZW5xbW14dG5ob2V4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzcxOTYwNTYsImV4cCI6MjA5Mjc3MjA1Nn0.iaLuNX0e8o_ks4Cd3S1W-4-BI60zyfIY1Mmqjaw_1zM";

// Returns null if the token is valid; otherwise a short reason string (used
// only as a truthy "invalid" signal — not surfaced to the user). Validity =
// HTTP 200 from /auth/v1/user.
async function verifyToken(token: string): Promise<string | null> {
  try {
    const resp = await fetch(`${SUPABASE_URL}/auth/v1/user`, {
      method: "GET",
      headers: {
        apikey: SUPABASE_ANON_KEY,
        Authorization: `Bearer ${token}`,
      },
    });
    if (resp.ok) return null;
    return `auth status ${resp.status}`;
  } catch (e) {
    return `network ${e instanceof Error ? e.message : String(e)}`;
  }
}

// =====================================================================
// Model registry & provider routing
// =====================================================================
//
// Built-in models live in BUILT_IN_MODELS — used as the source of truth when
// the frontend doesn't send an explicit `provider`. Custom models added by
// the user from the UI always send `provider` directly, so they don't need
// to be listed here.

const DEFAULT_MODEL_ID = "gemma-4-uncensored";

type Provider = "venice" | "openrouter";

interface BuiltInModel {
  provider: Provider;
  contextWindow?: number; // total context window in tokens
}

const BUILT_IN_MODELS: Record<string, BuiltInModel> = {
  "gemma-4-uncensored": { provider: "venice", contextWindow: 262144 }, // 256K
  "e2ee-gemma-4-26b-a4b-uncensored-p": { provider: "venice", contextWindow: 65536 }, // 64K
};

interface RequestBody {
  messages?: Array<{
    role: "system" | "user" | "assistant";
    content: string;
  }>;
  model?: string;
  // Frontend always sends `provider` so user-defined custom models can route
  // without us needing to register them server-side.
  provider?: Provider;
  // Supabase access token rides in the body (NOT the Authorization header)
  // because zo's public edge proxy strips Authorization before it reaches us.
  accessToken?: string;
}

// Defensive: zo's secrets UI sometimes stores values with surrounding quotes
// (the user can paste "sk-..." and the quotes get treated as part of the
// value). Trim them off + whitespace so the Bearer header is clean.
function cleanKey(raw: string | undefined): string | undefined {
  if (!raw) return undefined;
  let v = raw.trim();
  if (
    (v.startsWith('"') && v.endsWith('"')) ||
    (v.startsWith("'") && v.endsWith("'"))
  ) {
    v = v.slice(1, -1).trim();
  }
  return v;
}

function endpointFor(provider: Provider): {
  url: string;
  key: string | undefined;
  keyName: string;
} {
  if (provider === "venice") {
    return {
      url: "https://api.venice.ai/api/v1/chat/completions",
      key: cleanKey(process.env.VENICE_AI),
      keyName: "VENICE_AI",
    };
  }
  return {
    url: "https://openrouter.ai/api/v1/chat/completions",
    key: cleanKey(process.env.OPENROUTER_API_KEY),
    keyName: "OPENROUTER_API_KEY",
  };
}

// Same envelope shape on error and success so the frontend can always render
// the assistant's bubble. Friendly errors are surfaced as bubble text instead
// of bubbling up as red 500s.
function envelope(content: string) {
  return Response.json({
    choices: [{ message: { content } }],
  });
}

export default async function handler(c: Context): Promise<Response> {
  let body: RequestBody = {};
  try {
    body = (await c.req.json()) as RequestBody;
  } catch {
    return envelope("System: request body was not valid JSON.");
  }

  // --- Auth gate: validate the Supabase access token BEFORE spending credit ---
  // The token arrives in the request BODY (not the Authorization header) because
  // zo's public edge proxy strips Authorization. The body passes through intact.
  const token =
    typeof body.accessToken === "string" ? body.accessToken.trim() : null;
  if (!token) {
    return envelope(
      "System: please sign in again — no session token was sent with the request.",
    );
  }
  const authProblem = await verifyToken(token);
  if (authProblem) {
    return envelope(
      "System: your session couldn't be verified. Please sign in again.",
    );
  }

  const messages = Array.isArray(body.messages) ? body.messages : [];
  if (messages.length === 0) {
    return envelope("System: no messages were supplied.");
  }

  const modelId = body.model || DEFAULT_MODEL_ID;

  // Token-aware backstop (mirrors the client's chars/4 estimate). The client
  // already trims history well under the model's window, so a legit request is
  // always under this; it only rejects truly abusive payloads. Unknown/custom
  // model ids fall back to a generous default.
  const SERVER_CTX_FALLBACK = 262144; // 256K, matches the largest built-in
  const modelCtx = BUILT_IN_MODELS[modelId]?.contextWindow ?? SERVER_CTX_FALLBACK;
  const estTokens = messages.reduce(
    (n, m) => n + Math.ceil((m.content || "").length / 4),
    0,
  );
  if (estTokens > modelCtx) {
    return envelope(
      "System: conversation too long for this model's context window. Please start a new chat.",
    );
  }

  // Resolve provider: explicit value in body wins; otherwise look up in the
  // built-in registry. If neither matches, refuse rather than guessing.
  let provider: Provider;
  if (body.provider === "venice" || body.provider === "openrouter") {
    provider = body.provider;
  } else if (BUILT_IN_MODELS[modelId]) {
    provider = BUILT_IN_MODELS[modelId].provider;
  } else {
    return envelope(
      `System: unknown model "${modelId}" with no provider specified. ` +
        `Custom models must include a 'provider' field in the request.`,
    );
  }

  const { url, key, keyName } = endpointFor(provider);

  if (!key) {
    return envelope(
      `${keyName} is not configured on the server. Add it via zo's secrets UI (no surrounding quotes) and restart the space server.`,
    );
  }

  try {
    const upstream = await fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${key}`,
      },
      body: JSON.stringify({
        model: modelId,
        messages,
      }),
    });

    if (!upstream.ok) {
      const errText = await upstream.text();
      return envelope(
        `Upstream ${provider} returned ${upstream.status}: ${errText.slice(0, 500)}`,
      );
    }

    type ContentBlock = { type?: string; text?: string };
    type RawContent = string | ContentBlock[] | null | undefined;
    interface RawResponse {
      choices?: Array<{ message?: { content?: RawContent } }>;
    }

    const data = (await upstream.json()) as RawResponse;
    const raw: RawContent = data?.choices?.[0]?.message?.content;

    // Reasoning-model robustness: some models return content as an array of
    // blocks ([{type:"thinking",...}, {type:"text",text:"..."}]). Strip
    // thinking, keep text blocks, join. Pass plain strings through unchanged.
    // We're keeping this even though we're dropping Magistral, because future
    // models (or user-added custom ones) may use the same shape.
    function normalize(c: RawContent): string {
      if (typeof c === "string") return c;
      if (Array.isArray(c)) {
        const parts = c
          .filter((b) => b && b.type === "text" && typeof b.text === "string")
          .map((b) => b.text as string);
        if (parts.length > 0) return parts.join("\n\n");
      }
      return "(empty response from model)";
    }

    return Response.json({
      choices: [{ message: { content: normalize(raw) } }],
    });
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    return envelope(`Network error calling ${provider}: ${msg}`);
  }
}
