// CODE GENERATED BY SPACE TOOLS. DO NOT EDIT FILE. YOUR CHANGES WILL BE LOST.
import type { Context } from "hono";
import { signup, signin, refresh, verify, hasLegacyHash, upgradeLegacyPassword } from "../lib/surreal-auth";

// /api/auth — the site's front door, on our own box (SurrealDB record access).
// Contract (all POST, JSON):
//   { action:"signup",  email, pass }        -> { access, refresh, user:{id,email} }
//   { action:"signin",  email, pass }        -> same (transparently upgrades imported bcrypt -> argon2)
//   { action:"refresh", refresh }            -> { access, refresh }
//   { action:"me",      accessToken }        -> { user:{id,email} } | 401
//   { action:"signout" }                     -> { ok:true }  (stateless; client drops tokens)
// Errors are generic on purpose (no account enumeration).

const BAD_CREDS = "Email or password is incorrect.";

// --- tiny in-memory rate limiter (per process; resets on deploy) ---
const buckets = new Map<string, { n: number; reset: number }>();
function limited(key: string, max: number, windowMs: number): boolean {
  const now = Date.now();
  const b = buckets.get(key);
  if (!b || b.reset < now) { buckets.set(key, { n: 1, reset: now + windowMs }); return false; }
  b.n += 1;
  return b.n > max;
}
function clientIp(c: Context): string {
  return c.req.header("x-forwarded-for")?.split(",")[0].trim() || c.req.header("cf-connecting-ip") || "unknown";
}

const isEmail = (s: string) => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s) && s.length <= 254;

export default async function handler(c: Context): Promise<Response> {
  let body: { action?: string; email?: string; pass?: string; refresh?: string; accessToken?: string } = {};
  try {
    body = (await c.req.json()) as typeof body;
  } catch {
    return c.json({ error: "request body was not valid JSON" }, 400);
  }
  const ip = clientIp(c);
  const email = typeof body.email === "string" ? body.email.trim().toLowerCase() : "";
  const pass = typeof body.pass === "string" ? body.pass : "";

  if (body.action === "signup") {
    if (limited(`su:${ip}`, 5, 60 * 60 * 1000)) return c.json({ error: "Too many signups from this network. Try later." }, 429);
    if (!isEmail(email)) return c.json({ error: "Please enter a valid email." }, 400);
    if (pass.length < 8) return c.json({ error: "Password must be at least 8 characters." }, 400);
    const tokens = await signup(email, pass);
    if (!tokens) return c.json({ error: "Could not create that account. If you already have one, sign in instead." }, 409);
    const user = await verify(tokens.access);
    return c.json({ access: tokens.access, refresh: tokens.refresh, user });
  }

  if (body.action === "signin") {
    if (limited(`si:${ip}`, 10, 15 * 60 * 1000) || (email && limited(`se:${email}`, 10, 15 * 60 * 1000))) {
      return c.json({ error: "Too many attempts. Please wait 15 minutes." }, 429);
    }
    if (!isEmail(email) || !pass) return c.json({ error: BAD_CREDS }, 401);
    const tokens = await signin(email, pass);
    if (!tokens) return c.json({ error: BAD_CREDS }, 401);
    const user = await verify(tokens.access);
    if (!user) return c.json({ error: BAD_CREDS }, 401);
    // Imported Supabase account? Upgrade its hash to argon2 now that we hold the
    // plaintext for this one request. Failure here must never block signin.
    try {
      if (await hasLegacyHash(user.id)) await upgradeLegacyPassword(user.id, pass);
    } catch (e) {
      console.error("[auth] legacy upgrade failed:", (e as Error).message);
    }
    return c.json({ access: tokens.access, refresh: tokens.refresh, user });
  }

  if (body.action === "refresh") {
    const rt = typeof body.refresh === "string" ? body.refresh.trim() : "";
    if (!rt) return c.json({ error: "no refresh token" }, 401);
    const tokens = await refresh(rt);
    if (!tokens) return c.json({ error: "session expired" }, 401);
    return c.json({ access: tokens.access, refresh: tokens.refresh });
  }

  if (body.action === "me") {
    const at = typeof body.accessToken === "string" ? body.accessToken.trim() : "";
    const user = at ? await verify(at) : null;
    if (!user) return c.json({ error: "unauthorized" }, 401);
    return c.json({ user });
  }

  if (body.action === "signout") {
    return c.json({ ok: true });
  }

  return c.json({ error: "unknown action" }, 400);
}
