// CODE GENERATED BY SPACE TOOLS. DO NOT EDIT FILE. YOUR CHANGES WILL BE LOST.
import type { Context } from "hono";
import { getUser } from "../lib/api-auth";
import { surrealQuery, str, thing } from "../lib/surreal-client";
import { analyzeDocument, convertWithModel, speakerSummary, IMPORT_MAX_BYTES, estimateTokens } from "../lib/import-convert";
import { parseActm, formatActm, type ActmDoc } from "../lib/actm";
import { mirrorMessages, type MirrorMessage } from "../lib/memory-mirror";

// /api/import v1.1 (2026-09-09) — bring documents & transcripts into memory / context.
//
//   { action:"analyze", accessToken, text, filename? }
//      -> { format, needsConvert, chars, tokenEstimate, title, speakers:[{name,turns}], turnCount, preview:[{speaker,text}] }
//         (needsConvert:true → call convert first, then analyze the returned ACTM)
//   { action:"convert", accessToken, text }                 -> { jobId }   result = ACTM markdown (poll /api/chat-status)
//   { action:"commit",  accessToken, text, filename?, title, mapping:{<speaker>: "being"|"me"|"other"},
//                       targetThreadId, mode:"memory"|"context", tzOffsetMinutes?, contextBudgetTokens? }
//      -> { jobId }   result = JSON { threadId, title, turns, injected:[messages], truncated, indexCard }
//
// Every import creates a VISIBLE "📥 <title>" thread (verbatim, whole document,
// mirrored into memory with speaker names). In context mode the caller ALSO gets
// the recent turns that fit its budget to append to the current chat, flagged
// imported (the live mirror skips those — no double memory) plus an index card
// when truncated. Being ownership: the new thread inherits the target chat's
// being_id and is_private. Jobs reuse the chat_job table (kind = "import").

interface Body {
  action?: string; accessToken?: string; text?: string; filename?: string; title?: string;
  mapping?: Record<string, string>; targetThreadId?: string; mode?: string; contextBudgetTokens?: number;
  treatAsConversation?: boolean; // force the converter when a document has no speaker labels
}

const newId = (p: string) => `${p}${Date.now().toString(36)}${Math.random().toString(36).slice(2, 8)}`;

export default async function handler(c: Context): Promise<Response> {
  let body: Body = {};
  try { body = (await c.req.json()) as Body; } catch { return c.json({ error: "request body was not valid JSON" }, 400); }
  const token = typeof body.accessToken === "string" ? body.accessToken.trim() : "";
  const user = token ? await getUser(token) : null;
  if (!user) return c.json({ error: "unauthorized" }, 401);
  const uid = user.id;

  const text = typeof body.text === "string" ? body.text : "";
  if (body.action === "analyze" || body.action === "convert" || body.action === "commit") {
    if (!text.trim()) return c.json({ error: "nothing to import — paste text or choose a file" }, 400);
    if (text.length > IMPORT_MAX_BYTES) return c.json({ error: `That's over the 5 MB limit — please split the file and import it in parts.` }, 413);
  }

  // ---------------------------------------------------------------- analyze
  if (body.action === "analyze") {
    const a = analyzeDocument(text, body.filename, body.treatAsConversation === true);
    if (a.needsConvert || !a.doc) {
      return c.json({ format: a.format, needsConvert: true, chars: a.chars, tokenEstimate: a.tokenEstimate });
    }
    return c.json({
      format: a.format, needsConvert: false, chars: a.chars, tokenEstimate: a.tokenEstimate,
      title: a.doc.title, speakers: speakerSummary(a.doc), turnCount: a.doc.turns.length,
      preview: a.doc.turns.slice(0, 6).map((t) => ({ speaker: t.speaker, text: t.text.slice(0, 220) })),
    });
  }

  // ---------------------------------------------------------------- convert (job)
  if (body.action === "convert") {
    const jobId = newId("imp");
    const jobRid = thing("chat_job", jobId);
    await surrealQuery(`CREATE ${jobRid} SET user_id = ${str(uid)}, kind = "import", status = "running", phase = "converting", partial = "";`);
    void (async () => {
      try {
        const doc = await convertWithModel(text, async (done, total) => {
          await surrealQuery(`UPDATE ${jobRid} SET phase = ${str(`converting ${done}/${total}`)} WHERE status = "running";`).catch(() => {});
        });
        await surrealQuery(`UPDATE ${jobRid} SET status = "done", phase = "done", result = ${str(formatActm(doc))} WHERE status = "running";`);
      } catch (e) {
        await surrealQuery(`UPDATE ${jobRid} SET status = "error", phase = "error", error = ${str(String((e as Error).message ?? e).slice(0, 400))} WHERE status = "running";`).catch(() => {});
      }
    })();
    return c.json({ jobId });
  }

  // ---------------------------------------------------------------- commit (job)
  if (body.action === "commit") {
    const mode = body.mode === "context" ? "context" : "memory";
    const targetThreadId = (body.targetThreadId ?? "").trim();
    if (!targetThreadId) return c.json({ error: "targetThreadId required" }, 400);
    const mapping = body.mapping && typeof body.mapping === "object" ? body.mapping : {};

    // Ownership + inheritance (being, privacy) from the target chat.
    const chk = await surrealQuery<Array<{ id: unknown; being_id?: string | null; is_private?: boolean }>>(
      `SELECT id, being_id, is_private FROM thread WHERE id = ${thing("thread", targetThreadId)} AND user_id = ${str(uid)};`
    );
    const target = (chk[0] ?? [])[0];
    if (!target) return c.json({ error: "target chat not found" }, 404);
    const beingIdFull = target.being_id ? `being:${String(target.being_id).replace(/^being:/, "").replace(/`/g, "")}` : null;
    const isPrivate = target.is_private === true;

    // Parse (deterministic; if it still needs the model the client should have converted first)
    const a = analyzeDocument(text, body.filename);
    let doc: ActmDoc | null = a.doc;
    if (!doc) {
      if (looksLikeActmSafe(text)) doc = parseActm(text);
      else return c.json({ error: "this document needs conversion first — call convert, then commit the result" }, 400);
    }
    if (!doc || doc.turns.length === 0) return c.json({ error: "no text found to import" }, 400);
    const title = (body.title ?? "").trim().slice(0, 120) || doc.title || "Imported document";

    // Every speaker must be defined (Sam: nobody is assumed).
    const speakers = speakerSummary(doc).map((s) => s.name);
    const missing = speakers.filter((s) => !["being", "me", "other"].includes(mapping[s] ?? ""));
    if (missing.length) return c.json({ error: `please say who each speaker is: ${missing.join(", ")}`, missing }, 400);

    const jobId = newId("imp");
    const jobRid = thing("chat_job", jobId);
    await surrealQuery(`CREATE ${jobRid} SET user_id = ${str(uid)}, kind = "import", status = "running", phase = "preparing", partial = "";`);

    void (async () => {
      try {
        // Build messages, verbatim, in order. Synthetic times keep order when the source has none.
        const base = Date.now() - doc!.turns.length * 1000;
        const messages: MirrorMessage[] = doc!.turns.map((t, i) => ({
          id: newId("m"),
          text: t.text,
          type: mapping[t.speaker] === "being" ? "ai" : "user",
          ts: t.ts ?? base + i * 1000,
          speaker: t.speaker,
          imported: true,
        }));
        // Duplicate guard: same content already imported into this account?
        const hash = await sha256(doc!.turns.map((t) => t.text).join("\n"));
        const dup = await surrealQuery<Array<{ id: unknown; name?: string }>>(
          `SELECT id, name FROM thread WHERE user_id = ${str(uid)} AND import_hash = ${str(hash)};`
        );
        const dupName = (dup[0] ?? [])[0]?.name ?? null;

        // The visible 📥 thread (whole document, verbatim)
        const threadId = newId("imp");
        const threadName = `📥 ${title}`;
        await surrealQuery(
          `CREATE ${thing("thread", threadId)} SET
            user_id = ${str(uid)}, name = ${str(threadName)}, model_id = NONE, system_prompt_id = NONE,
            messages = ${JSON.stringify(messages)}, updated_at = time::now(),
            being_id = ${beingIdFull ? str(beingIdFull) : "NONE"}, is_private = ${isPrivate ? "true" : "false"}, memory_mode = "cloud",
            import_hash = ${str(hash)}, import_source = ${str(doc!.source)}, imported_from = ${str(targetThreadId)};
           ${beingIdFull ? `RELATE ${thing("being", beingIdFull.replace(/^being:/, ""))}->declared->${thing("thread", threadId)};` : ""}`
        );
        await surrealQuery(`UPDATE ${jobRid} SET phase = ${str(`remembering 0/${messages.length}`)} WHERE status = "running";`);

        // Mirror + embed everything (private threads are never mirrored — same rule as live chat)
        let written = 0;
        if (!isPrivate) {
          const r = await mirrorMessages(uid, threadId, beingIdFull, messages, async (done, total) => {
            await surrealQuery(`UPDATE ${jobRid} SET phase = ${str(`remembering ${done}/${total}`)} WHERE status = "running";`).catch(() => {});
          });
          written = r.written;
        }

        // Context mode: the recent turns that fit the caller's budget + an index card if truncated
        let injected: MirrorMessage[] = [];
        let truncated = false;
        let indexCard: string | null = null;
        if (mode === "context") {
          const budget = typeof body.contextBudgetTokens === "number" && body.contextBudgetTokens > 0 ? body.contextBudgetTokens : 60_000;
          let used = 0;
          for (let i = messages.length - 1; i >= 0; i--) {
            const t = estimateTokens(messages[i].text) + 8;
            if (used + t > budget) { truncated = true; break; }
            used += t;
            injected.unshift(messages[i]);
          }
          if (truncated) {
            const first = messages[0].ts ? fmt(messages[0].ts) : "?";
            const last = messages[messages.length - 1].ts ? fmt(messages[messages.length - 1].ts!) : "?";
            indexCard = `📄 Imported "${title}" — ${messages.length} turns, ${first} to ${last}. The most recent ${injected.length} are above; the whole document is in memory (chat "${threadName}") — ask me and I'll recall it.`;
          }
        }
        // context-injected copies get fresh ids so the current chat can hold them
        injected = injected.map((m) => ({ ...m, id: newId("m") }));

        const result = JSON.stringify({ threadId, title: threadName, turns: messages.length, remembered: written, injected, truncated, indexCard, duplicateOf: dupName });
        await surrealQuery(`UPDATE ${jobRid} SET status = "done", phase = "done", result = ${str(result)} WHERE status = "running";`);
      } catch (e) {
        await surrealQuery(`UPDATE ${jobRid} SET status = "error", phase = "error", error = ${str(String((e as Error).message ?? e).slice(0, 400))} WHERE status = "running";`).catch(() => {});
      }
    })();
    return c.json({ jobId });
  }

  return c.json({ error: "unknown action" }, 400);
}

function looksLikeActmSafe(s: string): boolean {
  return /^\s*---\s*\n[\s\S]*?\n---\s*\n/.test(s) && /^### .+/m.test(s);
}

function fmt(ts: number): string {
  const d = new Date(ts);
  return `${String(d.getMonth() + 1).padStart(2, "0")}/${String(d.getDate()).padStart(2, "0")}/${String(d.getFullYear()).slice(-2)}`;
}

async function sha256(s: string): Promise<string> {
  const buf = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(s));
  return [...new Uint8Array(buf)].map((b) => b.toString(16).padStart(2, "0")).join("");
}
