// CODE GENERATED BY SPACE TOOLS. DO NOT EDIT FILE. YOUR CHANGES WILL BE LOST.
import type { Context } from "hono";
import { SUPABASE_URL, SUPABASE_ANON_KEY, getUser } from "../lib/api-auth";

// Shares the same Supabase project constants as api-chat.ts.
interface SessionIn {
  id: string;
  name: string;
  messages: unknown[];
  systemPromptId: string | null;
  modelId: string;
  updatedAt?: number; // ms epoch from the client; preserved so ordering reflects real use
}

export default async function handler(c: Context): Promise<Response> {
  let body: { action?: string; accessToken?: string; sessions?: SessionIn[] } = {};
  try {
    body = (await c.req.json()) as typeof body;
  } catch {
    return c.json({ error: "request body was not valid JSON" }, 400);
  }

  // Token rides in the BODY (zo's public edge strips the Authorization header).
  const token = typeof body.accessToken === "string" ? body.accessToken.trim() : "";
  const user = token ? await getUser(token) : null;
  if (!user) return c.json({ error: "unauthorized" }, 401);

  const REST = `${SUPABASE_URL}/rest/v1/chats`;
  // WHY BOTH HEADERS — do NOT "simplify" by dropping one, it becomes a bug:
  //   apikey        = project's anon key  -> identifies WHICH Supabase project
  //   Authorization = user's access token -> identifies WHO the user is, so
  //                   Postgres RLS scopes every row to them (auth.uid() = user_id).
  // anon-key-only = no user -> RLS denies.  user-token-only = no project routing.
  const H: Record<string, string> = {
    apikey: SUPABASE_ANON_KEY,
    Authorization: `Bearer ${token}`,
    "Content-Type": "application/json",
  };

  // LOAD: RLS auto-filters to this user's own rows.
  if (body.action === "load") {
    const r = await fetch(`${REST}?select=*&order=updated_at.desc`, { headers: H });
    if (!r.ok) return c.json({ error: `load failed (${r.status})` }, 502);
    const rows = (await r.json()) as Array<Record<string, unknown>>;
    const sessions = rows.map((x) => ({
      id: x.id,
      name: x.name,
      messages: Array.isArray(x.messages) ? x.messages : [],
      systemPromptId: (x.system_prompt_id as string | null) ?? null,
      modelId: (x.model_id as string | null) ?? "gemma-4-uncensored",
      updatedAt:
        typeof x.updated_at === "string" ? Date.parse(x.updated_at as string) || 0 : 0,
    }));
    return c.json({ sessions });
  }

  // SAVE: upsert the current sessions, then delete only the rows that are gone.
  if (body.action === "save") {
    const sessions = Array.isArray(body.sessions) ? body.sessions : [];
    if (sessions.length === 0) return c.json({ ok: true, saved: 0 }); // never wipe on empty
    const rows = sessions.map((s) => ({
      id: s.id,
      user_id: user.id,
      name: s.name,
      model_id: s.modelId ?? null,
      system_prompt_id: s.systemPromptId ?? null,
      messages: Array.isArray(s.messages) ? s.messages : [],
      // Preserve the client's per-chat timestamp. Stamping now() here for every
      // row gave ALL chats identical updated_at on every batch save, which made
      // recency ordering impossible (the July 2026 list-shuffle bug).
      updated_at:
        typeof s.updatedAt === "number" && isFinite(s.updatedAt) && s.updatedAt > 0
          ? new Date(s.updatedAt).toISOString()
          : new Date().toISOString(),
    }));
    const up = await fetch(`${REST}?on_conflict=id`, {
      method: "POST",
      headers: { ...H, Prefer: "resolution=merge-duplicates,return=minimal" },
      body: JSON.stringify(rows),
    });
    if (!up.ok) {
      const detail = (await up.text()).slice(0, 300);
      return c.json({ error: `save failed (${up.status})`, detail }, 502);
    }

    // Delete-reconcile: read this user's cloud ids (RLS-scoped), delete only the
    // stale ones (those not in the current keep-set) in ONE roundtrip via the
    // PostgREST not.in. operator. The keep-set is the small one in practice
    // (usually <50), so the query string stays well under URL length limits.
    //
    // Belt-and-suspenders: the SAVE branch above already short-circuits when
    // sessions.length === 0, so we never reach here with an empty keep-set. We
    // assert it defensively anyway — an empty not.in.() means "match nothing",
    // which would silently delete every cloud row for this user.
    const keep = new Set(rows.map((r) => r.id));
    if (keep.size === 0) {
      return c.json({ ok: true, saved: rows.length, note: "skipped reconcile: empty keep-set" });
    }
    const cur = await fetch(`${REST}?select=id`, { headers: H });
    if (cur.ok) {
      const ids = (await cur.json()) as Array<{ id: string }>;
      const hasStale = ids.some((x) => !keep.has(x.id));
      if (hasStale) {
        const keepList = [...keep].map((id) => encodeURIComponent(id)).join(",");
        await fetch(
          `${REST}?id=not.in.(${keepList})&user_id=eq.${encodeURIComponent(user.id)}`,
          { method: "DELETE", headers: H },
        );
      }
    }
    return c.json({ ok: true, saved: rows.length });
  }

  return c.json({ error: "unknown action" }, 400);
}
