// CODE GENERATED BY SPACE TOOLS. DO NOT EDIT FILE. YOUR CHANGES WILL BE LOST.
import type { Context } from "hono";
import { SUPABASE_URL, SUPABASE_ANON_KEY, getUser } from "../lib/api-auth";

// Same Supabase project constants as api-chat.ts / api-transcripts.ts.
export default async function handler(c: Context): Promise<Response> {
  let body: { action?: string; accessToken?: string; prefs?: Record<string, unknown> } = {};
  try {
    body = (await c.req.json()) as typeof body;
  } catch {
    return c.json({ error: "request body was not valid JSON" }, 400);
  }

  // Token rides in the BODY (zo's public edge strips Authorization).
  const token = typeof body.accessToken === "string" ? body.accessToken.trim() : "";
  const user = token ? await getUser(token) : null;
  if (!user) return c.json({ error: "unauthorized" }, 401);

  const REST = `${SUPABASE_URL}/rest/v1/user_prefs`;
  // apikey = project; Authorization = user -> RLS scopes to this user's row.
  const H: Record<string, string> = {
    apikey: SUPABASE_ANON_KEY,
    Authorization: `Bearer ${token}`,
    "Content-Type": "application/json",
  };

  // LOAD: return this user's prefs object ({} if they have no row yet).
  if (body.action === "load") {
    const r = await fetch(`${REST}?select=prefs`, { headers: H });
    if (!r.ok) return c.json({ error: `load failed (${r.status})` }, 502);
    const rows = (await r.json()) as Array<{ prefs?: Record<string, unknown> }>;
    return c.json({ prefs: (rows[0] && rows[0].prefs) || {} });
  }

  // SAVE: MERGE the posted keys into the existing prefs so we never clobber
  // other keys (fontIndex, theme, etc.) the client isn't managing yet.
  if (body.action === "save") {
    const incoming = body.prefs && typeof body.prefs === "object" ? body.prefs : {};
    const cur = await fetch(`${REST}?select=prefs`, { headers: H });
    const existing =
      cur.ok ? (((await cur.json()) as Array<{ prefs?: Record<string, unknown> }>)[0]?.prefs || {}) : {};
    const merged = { ...existing, ...incoming };
    const up = await fetch(`${REST}?on_conflict=user_id`, {
      method: "POST",
      headers: { ...H, Prefer: "resolution=merge-duplicates,return=minimal" },
      body: JSON.stringify([{ user_id: user.id, prefs: merged, updated_at: new Date().toISOString() }]),
    });
    if (!up.ok) {
      const detail = (await up.text()).slice(0, 300);
      return c.json({ error: `save failed (${up.status})`, detail }, 502);
    }
    return c.json({ ok: true });
  }

  return c.json({ error: "unknown action" }, 400);
}
