// CODE GENERATED BY SPACE TOOLS. DO NOT EDIT FILE. YOUR CHANGES WILL BE LOST.
import type { Context } from "hono";

// Same Supabase project constants as api-chat.ts / api-transcripts.ts.
const SUPABASE_URL =
  process.env.VITE_SUPABASE_URL ||
  process.env.SUPABASE_URL ||
  "https://oelfxzsaenqmmxtnhoex.supabase.co";
const SUPABASE_ANON_KEY =
  process.env.VITE_SUPABASE_ANON_KEY ||
  process.env.SUPABASE_ANON_KEY ||
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9lbGZ4enNhZW5xbW14dG5ob2V4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzcxOTYwNTYsImV4cCI6MjA5Mjc3MjA1Nn0.iaLuNX0e8o_ks4Cd3S1W-4-BI60zyfIY1Mmqjaw_1zM";

async function getUser(token: string): Promise<{ id: string } | null> {
  try {
    const r = await fetch(`${SUPABASE_URL}/auth/v1/user`, {
      headers: { apikey: SUPABASE_ANON_KEY, Authorization: `Bearer ${token}` },
    });
    if (!r.ok) return null;
    const u = (await r.json()) as { id?: string };
    return u && typeof u.id === "string" ? { id: u.id } : null;
  } catch {
    return null;
  }
}

export default async function handler(c: Context): Promise<Response> {
  let body: { action?: string; accessToken?: string; prefs?: Record<string, unknown> } = {};
  try {
    body = (await c.req.json()) as typeof body;
  } catch {
    return c.json({ error: "request body was not valid JSON" }, 400);
  }

  // Token rides in the BODY (zo's public edge strips Authorization).
  const token = typeof body.accessToken === "string" ? body.accessToken.trim() : "";
  const user = token ? await getUser(token) : null;
  if (!user) return c.json({ error: "unauthorized" }, 401);

  const REST = `${SUPABASE_URL}/rest/v1/user_prefs`;
  // apikey = project; Authorization = user -> RLS scopes to this user's row.
  const H: Record<string, string> = {
    apikey: SUPABASE_ANON_KEY,
    Authorization: `Bearer ${token}`,
    "Content-Type": "application/json",
  };

  // LOAD: return this user's prefs object ({} if they have no row yet).
  if (body.action === "load") {
    const r = await fetch(`${REST}?select=prefs`, { headers: H });
    if (!r.ok) return c.json({ error: `load failed (${r.status})` }, 502);
    const rows = (await r.json()) as Array<{ prefs?: Record<string, unknown> }>;
    return c.json({ prefs: (rows[0] && rows[0].prefs) || {} });
  }

  // SAVE: MERGE the posted keys into the existing prefs so we never clobber
  // other keys (fontIndex, theme, etc.) the client isn't managing yet.
  if (body.action === "save") {
    const incoming = body.prefs && typeof body.prefs === "object" ? body.prefs : {};
    const cur = await fetch(`${REST}?select=prefs`, { headers: H });
    const existing =
      cur.ok ? (((await cur.json()) as Array<{ prefs?: Record<string, unknown> }>)[0]?.prefs || {}) : {};
    const merged = { ...existing, ...incoming };
    const up = await fetch(`${REST}?on_conflict=user_id`, {
      method: "POST",
      headers: { ...H, Prefer: "resolution=merge-duplicates,return=minimal" },
      body: JSON.stringify([{ user_id: user.id, prefs: merged, updated_at: new Date().toISOString() }]),
    });
    if (!up.ok) {
      const detail = (await up.text()).slice(0, 300);
      return c.json({ error: `save failed (${up.status})`, detail }, 502);
    }
    return c.json({ ok: true });
  }

  return c.json({ error: "unknown action" }, 400);
}
