// CODE GENERATED BY SPACE TOOLS. DO NOT EDIT FILE. YOUR CHANGES WILL BE LOST.
import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { createClient } from "@supabase/supabase-js";

// `detectSessionInUrl: true` is the default. When Supabase redirects the user
// here after they click an email confirmation link, the SDK parses the URL
// hash, exchanges tokens, and fires an SIGNED_IN event automatically.
//
// Supabase env vars come from zo's secrets UI. Anon key is public-by-design.
const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL ||
  "https://oelfxzsaenqmmxtnhoex.supabase.co";
const SUPABASE_ANON_KEY =
  import.meta.env.VITE_SUPABASE_ANON_KEY ||
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9lbGZ4enNhZW5xbW14dG5ob2V4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzcxOTYwNTYsImV4cCI6MjA5Mjc3MjA1Nn0.iaLuNX0e8o_ks4Cd3S1W-4-BI60zyfIY1Mmqjaw_1zM";
const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

const css = `
* { box-sizing: border-box; }
html, body, #root { width: 100%; height: 100%; margin: 0; padding: 0; overflow: hidden; }
.cb-root {
  position: fixed; inset: 0;
  display: flex; flex-direction: column;
  align-items: center; justify-content: center;
  background: radial-gradient(ellipse at center, rgba(40, 20, 10, 0.95), rgba(5, 3, 8, 0.99));
  color: #f1dca7;
  font-family: 'Segoe UI', sans-serif;
  gap: 16px;
}
.cb-spinner {
  width: 36px; height: 36px;
  border: 3px solid rgba(241, 220, 167, 0.18);
  border-top-color: #f1dca7;
  border-radius: 50%;
  animation: cb-spin 0.9s linear infinite;
}
@keyframes cb-spin { to { transform: rotate(360deg); } }
.cb-msg { font-size: 14px; letter-spacing: 0.04em; }
.cb-error {
  max-width: 380px;
  text-align: center;
  font-size: 13px;
  line-height: 1.5;
  color: #ffb3a8;
  padding: 14px 18px;
  border: 1px solid rgba(220, 90, 70, 0.35);
  border-radius: 10px;
  background: rgba(220, 90, 70, 0.1);
}
.cb-link {
  display: inline-block;
  margin-top: 14px;
  padding: 10px 18px;
  border: 1px solid rgba(241, 220, 167, 0.4);
  border-radius: 8px;
  color: #f1dca7;
  text-decoration: none;
  font-size: 12px;
  letter-spacing: 0.1em;
  text-transform: uppercase;
  transition: background 0.2s;
}
.cb-link:hover { background: rgba(241, 220, 167, 0.08); }
`;

export default function Page() {
  const navigate = useNavigate();
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    // Some flows include an explicit error in the URL hash (expired token, etc).
    const hash = window.location.hash.startsWith("#")
      ? window.location.hash.slice(1)
      : window.location.hash;
    const params = new URLSearchParams(hash);
    const errParam = params.get("error_description") || params.get("error");
    if (errParam) {
      setError(errParam.replace(/\+/g, " "));
      return;
    }

    let active = true;
    let timeout: ReturnType<typeof setTimeout> | null = null;

    function done() {
      if (!active) return;
      // Land them on chat â they're signed in now.
      navigate("/chat", { replace: true });
    }

    // detectSessionInUrl is async â wait for SIGNED_IN, with a fallback poll.
    const { data: sub } = supabase.auth.onAuthStateChange((event, session) => {
      if (!active) return;
      if (event === "SIGNED_IN" && session) done();
    });

    // Fallback: also check if a session already exists (e.g. it processed immediately).
    supabase.auth.getSession().then(({ data }) => {
      if (!active) return;
      if (data.session) done();
    });

    // Hard timeout â if nothing happens, show a friendly error.
    timeout = setTimeout(() => {
      if (active) {
        setError(
          "We couldn't confirm your link. It may have expired or already been used. Try signing in.",
        );
      }
    }, 8000);

    return () => {
      active = false;
      if (timeout) clearTimeout(timeout);
      sub.subscription.unsubscribe();
    };
  }, [navigate]);

  if (error) {
    return (
      <div className="cb-root">
        <style>{css}</style>
        <div className="cb-error">{error}</div>
        <a
          href="/auth"
          className="cb-link"
          onClick={(e) => {
            e.preventDefault();
            navigate("/auth", { replace: true });
          }}
        >
          Go to sign in
        </a>
      </div>
    );
  }

  return (
    <div className="cb-root">
      <style>{css}</style>
      <div className="cb-spinner" />
      <div className="cb-msg">Confirming your account...</div>
    </div>
  );
}
