// CODE GENERATED BY SPACE TOOLS. DO NOT EDIT FILE. YOUR CHANGES WILL BE LOST.
import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { createClient, type Session } from "@supabase/supabase-js";

// Supabase env vars come from zo's secrets UI. Anon key is public-by-design.
const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL ||
  "https://oelfxzsaenqmmxtnhoex.supabase.co";
const SUPABASE_ANON_KEY =
  import.meta.env.VITE_SUPABASE_ANON_KEY ||
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9lbGZ4enNhZW5xbW14dG5ob2V4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzcxOTYwNTYsImV4cCI6MjA5Mjc3MjA1Nn0.iaLuNX0e8o_ks4Cd3S1W-4-BI60zyfIY1Mmqjaw_1zM";
const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

const css = `
@font-face {
  font-family: 'Mokgech';
  src: url('/fonts/mokgech.ttf') format('truetype');
  font-display: swap;
}

* { box-sizing: border-box; }
html, body, #root { width: 100%; height: 100%; margin: 0; padding: 0; overflow: hidden; }

.auth-root {
  position: fixed; inset: 0;
  display: flex; align-items: center; justify-content: center;
  background:
    radial-gradient(ellipse at 50% 30%, rgba(255, 180, 80, 0.18) 0%, transparent 60%),
    radial-gradient(ellipse at 50% 80%, rgba(40, 20, 10, 0.95) 0%, rgba(0, 0, 0, 0.98) 100%),
    #050308;
  font-family: 'Segoe UI', sans-serif;
  color: #f1dca7;
}

.auth-card {
  width: 92%; max-width: 400px;
  background: rgba(20, 12, 6, 0.85);
  border: 1px solid rgba(241, 220, 167, 0.18);
  border-radius: 16px;
  padding: 32px 28px 24px;
  box-shadow: 0 24px 64px rgba(0,0,0,0.7), 0 0 80px rgba(255, 180, 80, 0.08);
  backdrop-filter: blur(8px);
}

.auth-title {
  font-family: 'Mokgech', serif;
  font-size: clamp(1.7rem, 4.5vw, 2.4rem);
  text-align: center;
  color: #f1dca7;
  text-transform: uppercase;
  letter-spacing: 0.06em;
  line-height: 1.1;
  margin-bottom: 4px;
  text-shadow: 0 0 24px rgba(241, 220, 167, 0.25);
}

.auth-subtitle {
  text-align: center;
  font-size: 12px;
  color: rgba(241, 220, 167, 0.6);
  margin-bottom: 24px;
  letter-spacing: 0.04em;
}

.auth-tabs {
  display: flex;
  border-bottom: 1px solid rgba(241, 220, 167, 0.15);
  margin-bottom: 22px;
}
.auth-tab {
  flex: 1; padding: 10px 0;
  background: transparent;
  border: none;
  color: rgba(241, 220, 167, 0.5);
  font-size: 13px;
  font-weight: 500;
  cursor: pointer;
  border-bottom: 2px solid transparent;
  transition: color 0.2s, border-color 0.2s;
}
.auth-tab.active { color: #f1dca7; border-bottom-color: #f1dca7; }
.auth-tab:hover { color: rgba(241, 220, 167, 0.85); }

.auth-field { margin-bottom: 14px; }
.auth-label {
  display: block; font-size: 11px;
  color: rgba(241, 220, 167, 0.65);
  margin-bottom: 6px;
  letter-spacing: 0.06em;
  text-transform: uppercase;
}
.auth-input {
  width: 100%;
  background: rgba(0, 0, 0, 0.5);
  border: 1px solid rgba(241, 220, 167, 0.22);
  border-radius: 8px;
  padding: 11px 14px;
  color: #f1dca7;
  font-size: 14px;
  font-family: inherit;
  transition: border-color 0.2s, box-shadow 0.2s, background 0.2s;
  outline: none;
}
.auth-input::placeholder { color: rgba(241, 220, 167, 0.3); }
.auth-input:focus {
  border-color: rgba(241, 220, 167, 0.6);
  background: rgba(0, 0, 0, 0.65);
  box-shadow: 0 0 0 3px rgba(241, 220, 167, 0.08);
}
.auth-input.has-error { border-color: rgba(220, 90, 70, 0.7); }
.auth-input.has-error:focus { box-shadow: 0 0 0 3px rgba(220, 90, 70, 0.15); }

.field-hint {
  font-size: 11px;
  margin-top: 4px;
  min-height: 13px;
  letter-spacing: 0.02em;
}
.field-hint.error { color: #e58a7a; }
.field-hint.ok { color: #9ed68c; }

.auth-submit {
  width: 100%;
  padding: 12px;
  border: none;
  border-radius: 8px;
  background: linear-gradient(180deg, #d4a352 0%, #b8860b 100%);
  color: #1a0d05;
  font-size: 14px;
  font-weight: 600;
  letter-spacing: 0.04em;
  cursor: pointer;
  margin-top: 6px;
  transition: filter 0.2s, transform 0.1s;
}
.auth-submit:hover:not(:disabled) { filter: brightness(1.08); }
.auth-submit:active:not(:disabled) { transform: scale(0.99); }
.auth-submit:disabled { opacity: 0.55; cursor: not-allowed; }

.auth-divider {
  display: flex; align-items: center; gap: 12px;
  margin: 18px 0 14px;
  color: rgba(241, 220, 167, 0.35);
  font-size: 10px;
  letter-spacing: 0.2em;
  text-transform: uppercase;
}
.auth-divider::before, .auth-divider::after {
  content: ''; flex: 1; height: 1px;
  background: rgba(241, 220, 167, 0.15);
}

.auth-oauth {
  width: 100%;
  padding: 11px;
  border: 1px solid rgba(241, 220, 167, 0.22);
  border-radius: 8px;
  background: rgba(255, 255, 255, 0.04);
  color: rgba(241, 220, 167, 0.7);
  font-size: 13px;
  font-weight: 500;
  cursor: not-allowed;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 10px;
  transition: background 0.2s;
}
.auth-oauth .google-icon { width: 16px; height: 16px; }
.auth-oauth .coming-soon { font-size: 10px; opacity: 0.55; letter-spacing: 0.08em; text-transform: uppercase; margin-left: 6px; }

.auth-banner {
  margin-top: 14px; padding: 10px 12px;
  border-radius: 8px;
  font-size: 12px;
  line-height: 1.4;
  text-align: center;
  letter-spacing: 0.02em;
}
.auth-banner.error { background: rgba(220, 90, 70, 0.13); border: 1px solid rgba(220, 90, 70, 0.3); color: #ffb3a8; }
.auth-banner.success { background: rgba(158, 214, 140, 0.12); border: 1px solid rgba(158, 214, 140, 0.3); color: #c4e7b5; }

.spinner {
  display: inline-block;
  width: 14px; height: 14px;
  border: 2px solid rgba(26, 13, 5, 0.3);
  border-top-color: #1a0d05;
  border-radius: 50%;
  animation: spin 0.7s linear infinite;
  margin-right: 8px;
  vertical-align: middle;
}
@keyframes spin { to { transform: rotate(360deg); } }

.auth-back {
  display: block;
  text-align: center;
  margin-top: 18px;
  font-size: 11px;
  color: rgba(241, 220, 167, 0.4);
  text-decoration: none;
  letter-spacing: 0.08em;
  text-transform: uppercase;
  transition: color 0.2s;
}
.auth-back:hover { color: rgba(241, 220, 167, 0.7); }
`;

type Mode = "signin" | "signup";

export default function Page() {
  const navigate = useNavigate();
  const [mode, setMode] = useState<Mode>("signin");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [emailErr, setEmailErr] = useState("");
  const [passErr, setPassErr] = useState("");
  const [banner, setBanner] = useState<{ kind: "error" | "success"; text: string } | null>(null);
  const [loading, setLoading] = useState(false);
  const [sessionChecked, setSessionChecked] = useState(false);

  // If a session already exists, skip the auth page.
  useEffect(() => {
    let active = true;
    supabase.auth.getSession().then(({ data }) => {
      if (!active) return;
      if (data.session) {
        navigate("/chat", { replace: true });
      } else {
        setSessionChecked(true);
      }
    });
    return () => {
      active = false;
    };
  }, [navigate]);

  // Live-react to sign-in events from other tabs / email confirmation.
  useEffect(() => {
    const { data: sub } = supabase.auth.onAuthStateChange((_event, session: Session | null) => {
      if (session) {
        navigate("/chat", { replace: true });
      }
    });
    return () => sub.subscription.unsubscribe();
  }, [navigate]);

  function validateEmail(v: string): string {
    if (!v) return "Email is required.";
    // Light validation â Supabase enforces the real rules.
    if (!/^\S+@\S+\.\S+$/.test(v)) return "That doesn't look like a valid email.";
    return "";
  }

  function validatePassword(v: string, signupMode: boolean): string {
    if (!v) return "Password is required.";
    if (signupMode && v.length < 8) return "At least 8 characters.";
    return "";
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    setBanner(null);

    const eErr = validateEmail(email);
    const pErr = validatePassword(password, mode === "signup");
    setEmailErr(eErr);
    setPassErr(pErr);
    if (eErr || pErr) return;

    setLoading(true);
    try {
      if (mode === "signup") {
        const { error } = await supabase.auth.signUp({
          email,
          password,
          options: {
            emailRedirectTo: `${window.location.origin}/auth/callback`,
          },
        });
        if (error) {
          setBanner({ kind: "error", text: error.message });
        } else {
          setBanner({
            kind: "success",
            text: "Account created. Check your email and click the link to confirm.",
          });
          setPassword("");
        }
      } else {
        const { error } = await supabase.auth.signInWithPassword({ email, password });
        if (error) {
          setBanner({ kind: "error", text: error.message });
        }
        // onAuthStateChange handles the redirect on success.
      }
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      setBanner({ kind: "error", text: msg });
    } finally {
      setLoading(false);
    }
  }

  function switchMode(m: Mode) {
    setMode(m);
    setBanner(null);
    setEmailErr("");
    setPassErr("");
  }

  if (!sessionChecked) {
    return (
      <div className="auth-root">
        <style>{css}</style>
      </div>
    );
  }

  return (
    <div className="auth-root">
      <style>{css}</style>
      <div className="auth-card">
        <div className="auth-title">Welcome</div>
        <div className="auth-tabs" role="tablist">
          <button
            type="button"
            role="tab"
            aria-selected={mode === "signin"}
            className={`auth-tab${mode === "signin" ? " active" : ""}`}
            onClick={() => switchMode("signin")}
          >
            Sign in
          </button>
          <button
            type="button"
            role="tab"
            aria-selected={mode === "signup"}
            className={`auth-tab${mode === "signup" ? " active" : ""}`}
            onClick={() => switchMode("signup")}
          >
            Create account
          </button>
        </div>

        <form onSubmit={handleSubmit} noValidate>
          <div className="auth-field">
            <label className="auth-label" htmlFor="email">
              Email
            </label>
            <input
              id="email"
              type="email"
              autoComplete="email"
              autoFocus
              className={`auth-input${emailErr ? " has-error" : ""}`}
              value={email}
              onChange={(e) => {
                setEmail(e.target.value);
                if (emailErr) setEmailErr("");
              }}
              onBlur={() => setEmailErr(validateEmail(email))}
              placeholder="you@example.com"
              disabled={loading}
            />
            <div className={`field-hint${emailErr ? " error" : ""}`}>{emailErr}</div>
          </div>

          <div className="auth-field">
            <label className="auth-label" htmlFor="password">
              Password
            </label>
            <input
              id="password"
              type="password"
              autoComplete={mode === "signup" ? "new-password" : "current-password"}
              className={`auth-input${passErr ? " has-error" : ""}`}
              value={password}
              onChange={(e) => {
                setPassword(e.target.value);
                if (passErr) setPassErr("");
              }}
              onBlur={() => setPassErr(validatePassword(password, mode === "signup"))}
              placeholder={mode === "signup" ? "8+ characters" : "Your password"}
              disabled={loading}
            />
            <div className={`field-hint${passErr ? " error" : ""}`}>{passErr}</div>
          </div>

          <button type="submit" className="auth-submit" disabled={loading}>
            {loading && <span className="spinner" />}
            {mode === "signin" ? "Sign in" : "Create account"}
          </button>
        </form>

        {banner && <div className={`auth-banner ${banner.kind}`}>{banner.text}</div>}

        <div className="auth-divider">or</div>

        <button type="button" className="auth-oauth" disabled title="Coming soon">
          <svg className="google-icon" viewBox="0 0 48 48" xmlns="http://www.w3.org/2000/svg">
            <path
              fill="#FFC107"
              d="M43.6 20.5H42V20H24v8h11.3c-1.7 4.7-6.2 8-11.3 8-6.6 0-12-5.4-12-12s5.4-12 12-12c3.1 0 5.8 1.2 7.9 3l5.7-5.7C34.3 6.1 29.4 4 24 4 12.9 4 4 12.9 4 24s8.9 20 20 20 20-8.9 20-20c0-1.3-.1-2.4-.4-3.5z"
            />
            <path fill="#FF3D00" d="M6.3 14.7l6.6 4.8C14.7 16 19 12 24 12c3.1 0 5.8 1.2 7.9 3l5.7-5.7C34.3 6.1 29.4 4 24 4 16.3 4 9.7 8.3 6.3 14.7z" />
            <path fill="#4CAF50" d="M24 44c5.3 0 10.1-2 13.7-5.3l-6.3-5.3C29.3 35 26.8 36 24 36c-5.1 0-9.5-3.2-11.2-7.9l-6.5 5C9.6 39.7 16.3 44 24 44z" />
            <path
              fill="#1976D2"
              d="M43.6 20.5H42V20H24v8h11.3c-.8 2.3-2.3 4.2-4.2 5.5l6.3 5.3c-.4.4 6.7-4.9 6.7-14.8 0-1.3-.1-2.4-.4-3.5z"
            />
          </svg>
          Continue with Google
          <span className="coming-soon">Soon</span>
        </button>

        <a
          href="/"
          className="auth-back"
          onClick={(e) => {
            e.preventDefault();
            navigate("/");
          }}
        >
          â Back to the flight
        </a>
      </div>
    </div>
  );
}
