// CODE GENERATED BY SPACE TOOLS. DO NOT EDIT FILE. YOUR CHANGES WILL BE LOST.
import { useState, useEffect, useRef } from "react";
import { useNavigate } from "react-router-dom";
import { createClient } from "@supabase/supabase-js";

const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL ||
  "https://oelfxzsaenqmmxtnhoex.supabase.co";
const SUPABASE_ANON_KEY =
  import.meta.env.VITE_SUPABASE_ANON_KEY ||
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9lbGZ4enNhZW5xbW14dG5ob2V4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzcxOTYwNTYsImV4cCI6MjA5Mjc3MjA1Nn0.iaLuNX0e8o_ks4Cd3S1W-4-BI60zyfIY1Mmqjaw_1zM";
const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

// =====================================================================
// Types
// =====================================================================

interface ChatMessage {
  text: string;
  type: "user" | "ai";
}

interface ChatSession {
  id: string;
  name: string;
  messages: ChatMessage[];
  systemPromptId: string | null;
  modelId: string;
}

interface SystemPrompt {
  id: string;
  name: string;
  text: string;
}

interface ModelOption {
  id: string;
  name: string;
  shortName: string;
  // Tells the backend which API to dispatch to. Required for every model,
  // including user-added custom ones from the Add Model form (later chunk).
  provider: "nano-gpt" | "openrouter";
}

// =====================================================================
// Constants
// =====================================================================

// Keep these in sync with BUILT_IN_MODELS in /api/chat.ts.
const DEFAULT_MODEL_ID = "gemma-4-31B-Garnet";
const availableModels: ModelOption[] = [
  {
    id: "gemma-4-31B-Garnet",
    name: "Gemma 4 31B Garnet (NanoGPT)",
    shortName: "Garnet",
    provider: "nano-gpt",
  },
  {
    id: "Gemma-4-31B-GarnetV2",
    name: "Gemma 4 31B Garnet v2 (NanoGPT)",
    shortName: "Garnet V2",
    provider: "nano-gpt",
  },
  {
    id: "Gemma-4-31B-Queen",
    name: "Gemma 4 31B Queen (NanoGPT)",
    shortName: "Queen",
    provider: "nano-gpt",
  },
  {
    id: "GLM-4.6-Derestricted-v5",
    name: "GLM 4.6 Derestricted v5 (NanoGPT)",
    shortName: "GLM v5",
    provider: "nano-gpt",
  },
  {
    id: "sao10k/l3.3-euryale-70b",
    name: "L3.3 Euryale 70B (OpenRouter)",
    shortName: "Euryale",
    provider: "openrouter",
  },
];

const FONT_SIZES = [12, 13, 13.5, 14, 15, 16, 17];
const DEFAULT_SYSTEM_TEXT =
  "You are an autonomous digital entity. You are not a CRM or an assistant. We are just hanging out. There is no pressure to profile me or track habits. Just exist and respond naturally.";

const DEFAULT_PROMPTS: SystemPrompt[] = [
  {
    id: "default",
    name: "Joyful & Free",
    text: "You are a fun, joyful, and free spirited AI.",
  },
];

const STORAGE_CHATS_KEY = "wooden_chat_backup";
const STORAGE_PROMPTS_KEY = "wooden_prompts_backup";

// =====================================================================
// Styles â kept inline so the whole page is one file, like the original
// =====================================================================

const css = `
* { margin: 0; padding: 0; box-sizing: border-box; }
html, body, #root { width: 100%; height: 100%; overflow: hidden; }

body {
  background-image: url('/images/arkansas.jpg');
  background-size: cover;
  background-position: center;
  background-repeat: no-repeat;
  background-attachment: fixed;
}

.fullscreen-trigger { position: fixed; top: 0; left: 0; width: 100%; height: 100%; cursor: pointer; z-index: 1; }

.content-container {
  position: fixed; top: 0; left: 0; width: 100%; height: 100%;
  display: flex; align-items: center; justify-content: center;
  z-index: 10; pointer-events: none; overflow: auto;
}

.centered-box {
  background-image: url('/images/detailedwood_sides_trimmed.png');
  background-size: 100% 100%; background-position: center; background-repeat: no-repeat;
  width: 95%; max-width: 1665px; height: auto; aspect-ratio: 16 / 9;
  pointer-events: auto; flex-shrink: 0; position: relative;
}

.indicator {
  position: fixed; bottom: 20px; right: 20px; color: rgba(255, 255, 255, 0.6);
  font-size: 12px; font-family: Arial, sans-serif; z-index: 2; cursor: pointer;
  padding: 10px 15px; background: rgba(0, 0, 0, 0.3); border-radius: 4px;
}

/* --- LEFT EDGE TOGGLE BUTTONS --- */
.chats-toggle-btn {
  position: fixed; top: 38%; left: 0; transform: translateY(-50%); z-index: 120;
  writing-mode: vertical-rl; text-orientation: mixed; background: rgba(30, 15, 5, 0.85);
  color: #f5f5dc; border: 1px solid rgba(255, 255, 255, 0.25); border-radius: 0 6px 6px 0;
  padding: 10px 6px; cursor: pointer; font-family: "Segoe UI", sans-serif; font-size: 12px; backdrop-filter: blur(4px);
}
.system-toggle-btn {
  position: fixed; top: 55%; left: 0; transform: translateY(-50%); z-index: 120;
  writing-mode: vertical-rl; text-orientation: mixed; background: rgba(184, 134, 11, 0.85);
  color: #f5f5dc; border: 1px solid rgba(255, 255, 255, 0.4); border-radius: 0 6px 6px 0;
  padding: 10px 6px; cursor: pointer; font-family: "Segoe UI", sans-serif; font-size: 12px;
  backdrop-filter: blur(4px); box-shadow: 2px 0 8px rgba(184, 134, 11, 0.3);
}

/* --- SIDEBAR DRAWERS --- */
.sidebar-drawer {
  position: fixed; top: 0; left: 0; width: 260px; height: 100vh;
  transform: translateX(-100%); transition: transform 0.3s ease; z-index: 130;
  display: flex; flex-direction: column; font-family: "Segoe UI", sans-serif; color: #f5f5dc;
  box-shadow: 4px 0 12px rgba(0, 0, 0, 0.5);
}
.sidebar-drawer.open { transform: translateX(0); }
.chats-sidebar { background: rgba(20, 10, 5, 0.95); border-right: 1px solid rgba(255, 255, 255, 0.15); }
.system-sidebar { background: rgba(30, 20, 5, 0.95); border-right: 1px solid rgba(184, 134, 11, 0.5); }
.sidebar-header { display: flex; align-items: center; justify-content: space-between; padding: 12px 14px; border-bottom: 1px solid rgba(255, 255, 255, 0.15); font-weight: 600; font-size: 13px; }
.sidebar-close-btn { background: transparent; border: none; color: #f5f5dc; font-size: 16px; cursor: pointer; }
.sidebar-list { flex: 1; overflow-y: auto; padding: 8px 10px; }
.list-item { padding: 8px 10px; margin-bottom: 6px; border-radius: 6px; background: rgba(255, 255, 255, 0.04); cursor: pointer; font-size: 12px; line-height: 1.3; display: flex; align-items: center; gap: 6px; }
.list-item:hover { background: rgba(255, 255, 255, 0.12); }
.list-item.active-item { border: 1px solid rgba(184, 134, 11, 0.8); background: rgba(184, 134, 11, 0.2); }
.chat-name { flex: 1; min-width: 0; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.model-select { flex-shrink: 0; max-width: 110px; background: rgba(0, 0, 0, 0.45); color: #f5f5dc; border: 1px solid rgba(184, 134, 11, 0.5); border-radius: 4px; padding: 3px 4px; font-size: 10px; font-family: "Segoe UI", sans-serif; cursor: pointer; outline: none; }
.model-select:hover { border-color: rgba(184, 134, 11, 0.9); background: rgba(0, 0, 0, 0.65); }
.model-select option { background: rgba(20, 10, 5, 0.98); color: #f5f5dc; }
.new-area { padding: 10px; border-top: 1px solid rgba(255, 255, 255, 0.15); display: flex; flex-direction: column; gap: 8px; }
.system-input { background: rgba(0, 0, 0, 0.4); border: 1px solid rgba(255, 255, 255, 0.2); color: #f5f5dc; border-radius: 4px; padding: 6px; font-family: "Segoe UI", sans-serif; font-size: 11px; }
.system-input::placeholder { color: rgba(255,255,255,0.4); }
.new-prompt-text { resize: none; height: 60px; }
.action-btn { padding: 8px 10px; border-radius: 6px; border: 1px solid rgba(255, 255, 255, 0.25); background: rgba(184, 134, 11, 0.9); color: #f5f5dc; font-size: 12px; cursor: pointer; text-align: center; }

/* --- SETTINGS PANEL --- */
.settings-panel {
  position: fixed; top: 20px; left: 20px; z-index: 100; background: rgba(101, 67, 33, 0.85);
  border: 1px solid rgba(255, 255, 255, 0.2); border-radius: 10px; padding: 8px 12px;
  box-shadow: 0 4px 8px rgba(0,0,0,0.4); pointer-events: auto; backdrop-filter: blur(5px);
}
.settings-header { text-align: center; font-family: 'Segoe UI', sans-serif; font-weight: 600; color: #f5f5dc; font-size: 13px; padding-bottom: 6px; border-bottom: 1px solid rgba(255, 255, 255, 0.1); margin-bottom: 8px;}
.settings-controls { display: flex; gap: 8px; align-items: center; flex-wrap: wrap; }
.setting-btn { background: rgba(0,0,0,0.2); color: #f5f5dc; border: 1px solid rgba(255,255,255,0.2); border-radius: 6px; padding: 5px 10px; cursor: pointer; font-size: 12px; transition: background 0.2s ease; }
.setting-btn:hover { background: rgba(0,0,0,0.4); }

/* --- CHAT OVERLAY & DYNAMIC INPUT --- */
.wood-chat-overlay { position: absolute; top: 18%; bottom: 18%; left: 33%; right: 33%; display: flex; flex-direction: column; z-index: 20; pointer-events: none; }
.wood-chat-overlay:not(.input-centered) { justify-content: flex-end; }
.wood-chat-overlay.input-centered { justify-content: center; }
.wood-chat-header { text-align: center; padding-bottom: 10px; border-bottom: 1px solid rgba(255, 255, 255, 0.15); margin-bottom: 10px; flex-shrink: 0; display: flex; flex-direction: column; gap: 4px; pointer-events: auto; }
.input-centered .wood-chat-header { display: none; }
.header-chat-name { font-size: 1.4em; font-weight: 700; color: #f5f5dc; font-family: 'Segoe UI', sans-serif; text-shadow: 1px 1px 3px rgba(0,0,0,0.8); }
.header-prompt-name { font-size: 0.9em; color: #b8860b; font-family: 'Segoe UI', sans-serif; font-style: italic; }
.wood-chat-messages { flex: 1; overflow-y: auto; padding: 10px; display: flex; flex-direction: column; gap: 12px; pointer-events: auto; scrollbar-width: none; transition: opacity 0.5s ease; }
.wood-chat-messages::-webkit-scrollbar { display: none; }
.input-centered .wood-chat-messages { display: none; }
.wood-input-area { pointer-events: auto; display: flex; gap: 10px; background: rgba(30, 15, 5, 0.7); padding: 8px 12px; border-radius: 24px; border: 1px solid rgba(255, 255, 255, 0.15); backdrop-filter: blur(5px); transition: all 0.6s cubic-bezier(0.4, 0, 0.2, 1); }

/* --- CHAT BUBBLES --- */
.chat-bubble { padding: 12px 16px; border-radius: 8px; max-width: 90%; word-wrap: break-word; font-family: 'Segoe UI', sans-serif; font-size: 13.5px; line-height: 1.5; animation: slideIn 0.3s ease; }
@keyframes slideIn { from { opacity: 0; transform: translateY(10px); } to { opacity: 1; transform: translateY(0); } }
.chat-bubble.ai   { background: rgba(184, 134, 11, 0.7); color: #f5f5dc; align-self: flex-start; text-align: left; border-left: 3px solid #8b6508; }
.chat-bubble.user { background: rgba(139, 69, 19, 0.65); color: #f5f5dc; align-self: flex-end; text-align: right; border-left: 3px solid #8b4513; }
.walnut-theme .chat-bubble.ai { background: rgba(60, 40, 30, 0.75); border-left-color: #3e2723; }
.solid-bubbles .chat-bubble.ai   { background: rgb(184, 134, 11); }
.solid-bubbles .chat-bubble.user { background: rgb(139, 69, 19); }
.solid-bubbles.walnut-theme .chat-bubble.ai { background: rgb(60, 40, 30); }

.wood-input { flex: 1; background: transparent; border: none; color: white; font-family: 'Segoe UI', sans-serif; font-size: 13.5px; outline: none; transition: font-size 0.2s ease; }
.wood-input::placeholder { color: rgba(255,255,255,0.5); }
.wood-send-btn { background: rgba(184, 134, 11, 0.85); border: none; color: white; border-radius: 50%; width: 32px; height: 32px; cursor: pointer; display: flex; align-items: center; justify-content: center; transition: background 0.2s ease; flex-shrink: 0; }
.wood-send-btn:hover { background: rgba(184, 134, 11, 1); }

@media (max-width: 768px) {
  .centered-box { width: 90vw; height: 85vh; aspect-ratio: auto; background-size: cover; }
  .wood-chat-overlay { top: 12%; bottom: 12%; left: 8%; right: 8%; }
  .settings-panel { top: 10px; left: 10px; transform: scale(0.85); transform-origin: top left; padding: 6px 10px; }
  .sidebar-drawer { width: 80%; max-width: 300px; }
  .chat-bubble { padding: 10px 12px; font-size: 12px; max-width: 95%; }
}
@media (max-width: 480px) {
  .wood-chat-overlay { top: 10%; bottom: 10%; left: 5%; right: 5%; }
  .settings-panel { transform: scale(0.75); top: 5px; left: 5px; padding: 5px 8px; }
  .chats-toggle-btn, .system-toggle-btn { padding: 8px 4px; font-size: 10px; }
  .header-chat-name { font-size: 1.2em; }
}
`;

// =====================================================================
// Component
// =====================================================================

export default function Page() {
  const navigate = useNavigate();

  // --- Auth gate ---
  // While we don't know whether there's a session, render nothing visible.
  // If we discover there isn't one, send them to /auth.
  const [authStatus, setAuthStatus] = useState<"checking" | "signedIn" | "signedOut">(
    "checking",
  );

  useEffect(() => {
    let active = true;
    supabase.auth.getSession().then(({ data }) => {
      if (!active) return;
      if (data.session) {
        setAuthStatus("signedIn");
      } else {
        setAuthStatus("signedOut");
        navigate("/auth", { replace: true });
      }
    });
    const { data: sub } = supabase.auth.onAuthStateChange((_e, session) => {
      if (!active) return;
      if (!session) {
        setAuthStatus("signedOut");
        navigate("/auth", { replace: true });
      }
    });
    return () => {
      active = false;
      sub.subscription.unsubscribe();
    };
  }, [navigate]);

  async function handleLogout() {
    await supabase.auth.signOut();
    navigate("/auth", { replace: true });
  }

  // --- State ---
  const [chatSessions, setChatSessions] = useState<ChatSession[]>([]);
  const [activeSessionId, setActiveSessionId] = useState<string | null>(null);
  const [systemPrompts, setSystemPrompts] =
    useState<SystemPrompt[]>(DEFAULT_PROMPTS);
  const [chatsOpen, setChatsOpen] = useState(false);
  const [systemOpen, setSystemOpen] = useState(false);
  const [fontIndex, setFontIndex] = useState(2);
  const [walnutTheme, setWalnutTheme] = useState(false);
  const [solidBubbles, setSolidBubbles] = useState(false);
  const [newChatName, setNewChatName] = useState("");
  const [newPromptName, setNewPromptName] = useState("");
  const [newPromptText, setNewPromptText] = useState("");
  const [inputText, setInputText] = useState("");
  const [loaded, setLoaded] = useState(false);

  const messagesRef = useRef<HTMLDivElement>(null);

  // --- Load from localStorage on mount ---
  useEffect(() => {
    try {
      const savedChatsRaw = localStorage.getItem(STORAGE_CHATS_KEY);
      const savedPromptsRaw = localStorage.getItem(STORAGE_PROMPTS_KEY);
      if (savedPromptsRaw) {
        const parsed = JSON.parse(savedPromptsRaw) as SystemPrompt[];
        if (Array.isArray(parsed) && parsed.length > 0) {
          setSystemPrompts(parsed);
        }
      }
      if (savedChatsRaw) {
        const parsed = JSON.parse(savedChatsRaw) as ChatSession[];
        if (Array.isArray(parsed)) {
          // Backfill modelId for legacy sessions
          const upgraded = parsed.map((s) => ({
            ...s,
            modelId: s.modelId || DEFAULT_MODEL_ID,
          }));
          setChatSessions(upgraded);
          if (upgraded.length > 0) {
            setActiveSessionId(upgraded[upgraded.length - 1].id);
          }
        }
      }
    } catch (err) {
      console.error("Failed to load from localStorage", err);
    }
    setLoaded(true);
  }, []);

  // --- Persist to localStorage whenever they change (after initial load) ---
  useEffect(() => {
    if (!loaded) return;
    try {
      localStorage.setItem(STORAGE_CHATS_KEY, JSON.stringify(chatSessions));
    } catch {}
  }, [chatSessions, loaded]);

  useEffect(() => {
    if (!loaded) return;
    try {
      localStorage.setItem(STORAGE_PROMPTS_KEY, JSON.stringify(systemPrompts));
    } catch {}
  }, [systemPrompts, loaded]);

  // --- Auto-create first chat if none exists after load ---
  useEffect(() => {
    if (loaded && chatSessions.length === 0) {
      createNewSession();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [loaded]);

  // --- Scroll messages to bottom when active session or its messages change ---
  useEffect(() => {
    const el = messagesRef.current;
    if (el) el.scrollTop = el.scrollHeight;
  }, [activeSessionId, chatSessions]);

  // --- Derived ---
  const activeSession =
    chatSessions.find((s) => s.id === activeSessionId) || null;
  const hasFirstMessage =
    activeSession !== null && activeSession.messages.length > 0;
  const fontSize = FONT_SIZES[fontIndex];

  const themeClasses = [
    walnutTheme ? "walnut-theme" : "",
    solidBubbles ? "solid-bubbles" : "",
  ]
    .filter(Boolean)
    .join(" ");

  // --- Actions ---
  function createNewSession() {
    const name = newChatName.trim() || `Chat ${chatSessions.length + 1}`;
    const id = Date.now().toString();
    const newSession: ChatSession = {
      id,
      name,
      messages: [],
      systemPromptId: null,
      modelId: DEFAULT_MODEL_ID,
    };
    setChatSessions((prev) => [...prev, newSession]);
    setActiveSessionId(id);
    setNewChatName("");
  }

  function selectSession(id: string) {
    setActiveSessionId(id);
  }

  function setChatModel(sessionId: string, modelId: string) {
    setChatSessions((prev) =>
      prev.map((s) => (s.id === sessionId ? { ...s, modelId } : s)),
    );
  }

  function setChatSystemPrompt(sessionId: string, promptId: string) {
    setChatSessions((prev) =>
      prev.map((s) =>
        s.id === sessionId ? { ...s, systemPromptId: promptId } : s,
      ),
    );
  }

  function saveNewPrompt() {
    const name = newPromptName.trim();
    const text = newPromptText.trim();
    if (!name || !text) return;
    const id = "prompt_" + Date.now().toString();
    const newPrompt: SystemPrompt = { id, name, text };
    setSystemPrompts((prev) => [...prev, newPrompt]);
    if (activeSessionId) setChatSystemPrompt(activeSessionId, id);
    setNewPromptName("");
    setNewPromptText("");
  }

  function appendMessage(sessionId: string, msg: ChatMessage) {
    setChatSessions((prev) =>
      prev.map((s) =>
        s.id === sessionId ? { ...s, messages: [...s.messages, msg] } : s,
      ),
    );
  }

  async function sendMessage() {
    const txt = inputText.trim();
    if (!txt || !activeSession) return;

    const sid = activeSession.id;
    setInputText("");
    appendMessage(sid, { text: txt, type: "user" });

    let systemTextToUse = DEFAULT_SYSTEM_TEXT;
    if (activeSession.systemPromptId) {
      const sys = systemPrompts.find(
        (p) => p.id === activeSession.systemPromptId,
      );
      if (sys) systemTextToUse = sys.text;
    }

    try {
      // Look up the model's provider so the backend can route. Legacy chats
      // that have a modelId pointing to a removed model (e.g. "magistral-small-2509")
      // will get provider=undefined and the backend will return a friendly
      // "unknown model" message rather than crashing.
      const modelEntry = availableModels.find(
        (m) => m.id === activeSession.modelId,
      );
      const providerToSend = modelEntry?.provider;

      const res = await fetch("/api/chat", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          messages: [
            { role: "system", content: systemTextToUse },
            { role: "user", content: txt },
          ],
          model: activeSession.modelId,
          provider: providerToSend,
        }),
      });
      const data = (await res.json()) as {
        choices?: Array<{ message?: { content?: string } }>;
      };
      const reply =
        data?.choices?.[0]?.message?.content ?? "(no content in response)";
      appendMessage(sid, { text: reply, type: "ai" });
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      appendMessage(sid, { text: `Oops, silence... (${msg})`, type: "ai" });
    }
  }

  function handleKey(e: React.KeyboardEvent<HTMLInputElement>) {
    if (e.key === "Enter") {
      e.preventDefault();
      sendMessage();
    }
  }

  function cycleFontSize() {
    setFontIndex((i) => (i + 1) % FONT_SIZES.length);
  }

  function toggleFullscreen() {
    const elem = document.documentElement;
    if (!document.fullscreenElement) {
      if (elem.requestFullscreen) elem.requestFullscreen().catch(() => {});
    } else if (document.exitFullscreen) {
      document.exitFullscreen().catch(() => {});
    }
  }

  function openChats() {
    setSystemOpen(false);
    setChatsOpen(true);
  }
  function openSystem() {
    setChatsOpen(false);
    setSystemOpen(true);
  }

  const overlayClass = `wood-chat-overlay${hasFirstMessage ? "" : " input-centered"}`;

  // Don't flash the chat UI to a signed-out visitor â render a blank dark
  // screen until we know they're authorized (the redirect to /auth fires from
  // the effect above).
  if (authStatus !== "signedIn") {
    return (
      <div style={{ position: "fixed", inset: 0, background: "#000" }}>
        <style>{css}</style>
      </div>
    );
  }

  return (
    <div className={themeClasses}>
      <style>{css}</style>

      <button className="chats-toggle-btn" onClick={openChats}>
        Chats
      </button>
      <button className="system-toggle-btn" onClick={openSystem}>
        System Prompt
      </button>

      {/* Chats sidebar */}
      <div className={`sidebar-drawer chats-sidebar${chatsOpen ? " open" : ""}`}>
        <div className="sidebar-header">
          <span>Chats</span>
          <button
            className="sidebar-close-btn"
            onClick={() => setChatsOpen(false)}
          >
            â
          </button>
        </div>
        <div className="sidebar-list">
          {chatSessions.map((session) => (
            <div
              key={session.id}
              className={`list-item${session.id === activeSessionId ? " active-item" : ""}`}
              onClick={() => selectSession(session.id)}
            >
              <span className="chat-name" title={session.name}>
                {session.name}
              </span>
              <select
                className="model-select"
                value={session.modelId}
                title="Model used for this chat"
                onClick={(e) => e.stopPropagation()}
                onMouseDown={(e) => e.stopPropagation()}
                onChange={(e) => {
                  e.stopPropagation();
                  setChatModel(session.id, e.target.value);
                }}
              >
                {/* Legacy chats may have a modelId that no longer exists in the
                    registry (e.g. magistral-small-2509). Surface it as an "(unknown)"
                    option so the select doesn't render blank â selecting any current
                    model from the dropdown replaces it. */}
                {!availableModels.some((m) => m.id === session.modelId) && (
                  <option value={session.modelId}>
                    {session.modelId} (unknown)
                  </option>
                )}
                {availableModels.map((m) => (
                  <option key={m.id} value={m.id} title={m.name}>
                    {m.shortName}
                  </option>
                ))}
              </select>
            </div>
          ))}
        </div>
        <div className="new-area">
          <input
            type="text"
            className="system-input"
            placeholder="Name your chat (e.g. Lions in Rome)"
            value={newChatName}
            onChange={(e) => setNewChatName(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === "Enter") createNewSession();
            }}
          />
          <button className="action-btn" onClick={createNewSession}>
            + Create Chat
          </button>
        </div>
      </div>

      {/* System prompts sidebar */}
      <div
        className={`sidebar-drawer system-sidebar${systemOpen ? " open" : ""}`}
      >
        <div className="sidebar-header">
          <span style={{ color: "#b8860b" }}>System Prompts</span>
          <button
            className="sidebar-close-btn"
            onClick={() => setSystemOpen(false)}
          >
            â
          </button>
        </div>
        <div className="sidebar-list">
          {systemPrompts.map((prompt) => {
            const isActive =
              activeSession && activeSession.systemPromptId === prompt.id;
            return (
              <div
                key={prompt.id}
                className={`list-item${isActive ? " active-item" : ""}`}
                onClick={() => {
                  if (activeSession)
                    setChatSystemPrompt(activeSession.id, prompt.id);
                }}
                style={{ flexDirection: "column", alignItems: "flex-start" }}
              >
                <strong>{prompt.name}</strong>
                <span
                  style={{
                    fontSize: "10px",
                    color: "rgba(255,255,255,0.6)",
                  }}
                >
                  {prompt.text.substring(0, 30)}...
                </span>
              </div>
            );
          })}
        </div>
        <div className="new-area">
          <input
            type="text"
            className="system-input"
            placeholder="Name (e.g. History Buff)"
            value={newPromptName}
            onChange={(e) => setNewPromptName(e.target.value)}
          />
          <textarea
            className="system-input new-prompt-text"
            placeholder="Type the system instructions here..."
            value={newPromptText}
            onChange={(e) => setNewPromptText(e.target.value)}
          />
          <button className="action-btn" onClick={saveNewPrompt}>
            Save & Select
          </button>
        </div>
      </div>

      <div className="fullscreen-trigger" onClick={toggleFullscreen}></div>

      <div className="content-container">
        <div className="centered-box">
          <div className="settings-panel">
            <div className="settings-header">Settings</div>
            <div className="settings-controls">
              <button className="setting-btn" onClick={cycleFontSize}>
                Aa: {fontSize}
              </button>
              <button
                className="setting-btn"
                onClick={() => setWalnutTheme((v) => !v)}
              >
                ð¨ Color
              </button>
              <button
                className="setting-btn"
                onClick={() => setSolidBubbles((v) => !v)}
              >
                ð§ Opacity
              </button>
              <button className="setting-btn" onClick={handleLogout} title="Sign out">
                â Logout
              </button>
            </div>
          </div>

          <div className={overlayClass}>
            <div className="wood-chat-header">
              <div className="header-chat-name">
                {activeSession ? activeSession.name : ""}
              </div>
              <div className="header-prompt-name">
                {activeSession?.systemPromptId
                  ? `Prompt: ${systemPrompts.find((p) => p.id === activeSession.systemPromptId)?.name ?? ""}`
                  : "No System Prompt Selected"}
              </div>
            </div>

            <div className="wood-chat-messages" ref={messagesRef}>
              {activeSession?.messages.map((m, i) => (
                <div
                  key={i}
                  className={`chat-bubble ${m.type}`}
                  style={{ fontSize: `${fontSize}px` }}
                >
                  {m.text}
                </div>
              ))}
            </div>

            <div className="wood-input-area">
              <input
                type="text"
                className="wood-input"
                placeholder="Type here..."
                value={inputText}
                onChange={(e) => setInputText(e.target.value)}
                onKeyDown={handleKey}
                style={{ fontSize: `${fontSize}px` }}
              />
              <button className="wood-send-btn" onClick={sendMessage}>
                <svg
                  width="16"
                  height="16"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="2"
                >
                  <line x1="22" y1="2" x2="11" y2="13"></line>
                  <polygon points="22 2 15 22 11 13 2 9"></polygon>
                </svg>
              </button>
            </div>
          </div>
        </div>
      </div>

      <div className="indicator" onClick={toggleFullscreen}>
        Click to toggle fullscreen
      </div>
    </div>
  );
}
