// CODE GENERATED BY SPACE TOOLS. DO NOT EDIT FILE. YOUR CHANGES WILL BE LOST.
import { lazy, type ComponentType } from "react";

export interface PageRouteConfig {
  component: ComponentType;
  public: boolean;
}

export const pageRoutes: Record<string, PageRouteConfig> = {
  "/": {
    component: lazy(() => import("./_home")),
    public: true,
  },
  "/auth/callback": {
    component: lazy(() => import("./auth-callback")),
    public: true,
  },
  "/chat": {
    component: lazy(() => import("./chat")),
    public: true,
  },
  "/auth": {
    component: lazy(() => import("./auth")),
    public: true,
  },
};
